import { KeyCategory, KeycodeDefinition } from "../types";

// Static database of common QMK keycodes.
// Each entry: [code, label, category, ...aliases]
type RawEntry = [string, string, KeyCategory, ...string[]];

const raw: RawEntry[] = [
  // ── Alpha ──────────────────────────────────────────────
  ["KC_A", "A", "alpha", "a"],
  ["KC_B", "B", "alpha", "b"],
  ["KC_C", "C", "alpha", "c"],
  ["KC_D", "D", "alpha", "d"],
  ["KC_E", "E", "alpha", "e"],
  ["KC_F", "F", "alpha", "f"],
  ["KC_G", "G", "alpha", "g"],
  ["KC_H", "H", "alpha", "h"],
  ["KC_I", "I", "alpha", "i"],
  ["KC_J", "J", "alpha", "j"],
  ["KC_K", "K", "alpha", "k"],
  ["KC_L", "L", "alpha", "l"],
  ["KC_M", "M", "alpha", "m"],
  ["KC_N", "N", "alpha", "n"],
  ["KC_O", "O", "alpha", "o"],
  ["KC_P", "P", "alpha", "p"],
  ["KC_Q", "Q", "alpha", "q"],
  ["KC_R", "R", "alpha", "r"],
  ["KC_S", "S", "alpha", "s"],
  ["KC_T", "T", "alpha", "t"],
  ["KC_U", "U", "alpha", "u"],
  ["KC_V", "V", "alpha", "v"],
  ["KC_W", "W", "alpha", "w"],
  ["KC_X", "X", "alpha", "x"],
  ["KC_Y", "Y", "alpha", "y"],
  ["KC_Z", "Z", "alpha", "z"],

  // ── Numbers ────────────────────────────────────────────
  ["KC_1", "1", "number", "one", "!"],
  ["KC_2", "2", "number", "two", "@"],
  ["KC_3", "3", "number", "three", "#"],
  ["KC_4", "4", "number", "four", "$"],
  ["KC_5", "5", "number", "five", "%"],
  ["KC_6", "6", "number", "six", "^"],
  ["KC_7", "7", "number", "seven", "&"],
  ["KC_8", "8", "number", "eight", "*"],
  ["KC_9", "9", "number", "nine", "("],
  ["KC_0", "0", "number", "zero", ")"],

  // ── Function keys ──────────────────────────────────────
  ["KC_F1", "F1", "function"],
  ["KC_F2", "F2", "function"],
  ["KC_F3", "F3", "function"],
  ["KC_F4", "F4", "function"],
  ["KC_F5", "F5", "function"],
  ["KC_F6", "F6", "function"],
  ["KC_F7", "F7", "function"],
  ["KC_F8", "F8", "function"],
  ["KC_F9", "F9", "function"],
  ["KC_F10", "F10", "function"],
  ["KC_F11", "F11", "function"],
  ["KC_F12", "F12", "function"],
  ["KC_F13", "F13", "function"],
  ["KC_F14", "F14", "function"],
  ["KC_F15", "F15", "function"],
  ["KC_F16", "F16", "function"],
  ["KC_F17", "F17", "function"],
  ["KC_F18", "F18", "function"],
  ["KC_F19", "F19", "function"],
  ["KC_F20", "F20", "function"],
  ["KC_F21", "F21", "function"],
  ["KC_F22", "F22", "function"],
  ["KC_F23", "F23", "function"],
  ["KC_F24", "F24", "function"],

  // ── Modifiers ──────────────────────────────────────────
  ["KC_LCTL", "Ctrl", "modifier", "Control", "Left Control", "KC_LCTRL"],
  ["KC_RCTL", "RCtrl", "modifier", "Right Control", "KC_RCTRL"],
  ["KC_LSFT", "Shift", "modifier", "Left Shift", "KC_LSHIFT"],
  ["KC_RSFT", "RShift", "modifier", "Right Shift", "KC_RSHIFT"],
  ["KC_LALT", "Alt", "modifier", "Left Alt", "Option", "KC_LOPT"],
  ["KC_RALT", "RAlt", "modifier", "Right Alt", "AltGr", "KC_ROPT", "KC_ALGR"],
  ["KC_LGUI", "Cmd", "modifier", "Super", "Win", "Left GUI", "KC_LCMD", "KC_LWIN"],
  ["KC_RGUI", "RCmd", "modifier", "Right Super", "Right Win", "KC_RCMD", "KC_RWIN"],
  ["KC_HYPR", "Hyper", "modifier", "Ctrl+Shift+Alt+Cmd"],
  ["KC_MEH", "Meh", "modifier", "Ctrl+Shift+Alt"],

  // ── Navigation ─────────────────────────────────────────
  ["KC_UP", "\u2191", "navigation", "Up", "Up Arrow"],
  ["KC_DOWN", "\u2193", "navigation", "Down", "Down Arrow"],
  ["KC_LEFT", "\u2190", "navigation", "Left", "Left Arrow"],
  ["KC_RGHT", "\u2192", "navigation", "Right", "Right Arrow", "KC_RIGHT"],
  ["KC_HOME", "Home", "navigation"],
  ["KC_END", "End", "navigation"],
  ["KC_PGUP", "PgUp", "navigation", "Page Up"],
  ["KC_PGDN", "PgDn", "navigation", "Page Down", "KC_PGDOWN"],

  // ── Editing ────────────────────────────────────────────
  ["KC_ENT", "Enter", "alpha", "Return", "KC_ENTER"],
  ["KC_ESC", "Esc", "navigation", "Escape"],
  ["KC_BSPC", "Bksp", "navigation", "Backspace", "KC_BACKSPACE"],
  ["KC_TAB", "Tab", "alpha"],
  ["KC_SPC", "Space", "alpha", "Spacebar", "KC_SPACE"],
  ["KC_DEL", "Del", "navigation", "Delete", "KC_DELETE"],
  ["KC_INS", "Ins", "navigation", "Insert"],
  ["KC_CAPS", "Caps", "modifier", "Caps Lock", "KC_CAPSLOCK", "KC_CLCK"],

  // ── Symbols ────────────────────────────────────────────
  ["KC_MINS", "-", "symbol", "Minus", "Dash", "KC_MINUS"],
  ["KC_EQL", "=", "symbol", "Equal", "Equals", "KC_EQUAL"],
  ["KC_LBRC", "[", "symbol", "Left Bracket", "KC_LBRACKET"],
  ["KC_RBRC", "]", "symbol", "Right Bracket", "KC_RBRACKET"],
  ["KC_BSLS", "\\", "symbol", "Backslash", "KC_BACKSLASH"],
  ["KC_SCLN", ";", "symbol", "Semicolon", "KC_SEMICOLON", "KC_SCOLON"],
  ["KC_QUOT", "'", "symbol", "Quote", "Apostrophe", "KC_QUOTE"],
  ["KC_GRV", "`", "symbol", "Grave", "Backtick", "Tilde", "KC_GRAVE"],
  ["KC_COMM", ",", "symbol", "Comma", "KC_COMMA"],
  ["KC_DOT", ".", "symbol", "Period", "Dot"],
  ["KC_SLSH", "/", "symbol", "Slash", "Forward Slash", "KC_SLASH"],
  ["KC_NUBS", "\\", "symbol", "Non-US Backslash"],
  ["KC_NUHS", "#", "symbol", "Non-US Hash"],

  // ── Shifted symbols (explicitly placed) ────────────────
  ["KC_TILD", "~", "symbol", "Tilde"],
  ["KC_EXLM", "!", "symbol", "Exclamation", "Bang"],
  ["KC_AT", "@", "symbol", "At"],
  ["KC_HASH", "#", "symbol", "Hash", "Pound"],
  ["KC_DLR", "$", "symbol", "Dollar"],
  ["KC_PERC", "%", "symbol", "Percent"],
  ["KC_CIRC", "^", "symbol", "Caret", "Circumflex"],
  ["KC_AMPR", "&", "symbol", "Ampersand"],
  ["KC_ASTR", "*", "symbol", "Asterisk", "Star"],
  ["KC_LPRN", "(", "symbol", "Left Parenthesis", "Left Paren"],
  ["KC_RPRN", ")", "symbol", "Right Parenthesis", "Right Paren"],
  ["KC_UNDS", "_", "symbol", "Underscore"],
  ["KC_PLUS", "+", "symbol", "Plus"],
  ["KC_LCBR", "{", "symbol", "Left Curly Brace"],
  ["KC_RCBR", "}", "symbol", "Right Curly Brace"],
  ["KC_PIPE", "|", "symbol", "Pipe"],
  ["KC_COLN", ":", "symbol", "Colon"],
  ["KC_DQUO", "\"", "symbol", "Double Quote"],
  ["KC_LABK", "<", "symbol", "Less Than", "Left Angle Bracket"],
  ["KC_RABK", ">", "symbol", "Greater Than", "Right Angle Bracket"],
  ["KC_QUES", "?", "symbol", "Question Mark"],

  // ── Numpad ─────────────────────────────────────────────
  ["KC_NUM", "Num", "modifier", "Num Lock", "KC_NUM_LOCK", "KC_NLCK"],
  ["KC_P1", "N1", "number", "Numpad 1", "KC_KP_1"],
  ["KC_P2", "N2", "number", "Numpad 2", "KC_KP_2"],
  ["KC_P3", "N3", "number", "Numpad 3", "KC_KP_3"],
  ["KC_P4", "N4", "number", "Numpad 4", "KC_KP_4"],
  ["KC_P5", "N5", "number", "Numpad 5", "KC_KP_5"],
  ["KC_P6", "N6", "number", "Numpad 6", "KC_KP_6"],
  ["KC_P7", "N7", "number", "Numpad 7", "KC_KP_7"],
  ["KC_P8", "N8", "number", "Numpad 8", "KC_KP_8"],
  ["KC_P9", "N9", "number", "Numpad 9", "KC_KP_9"],
  ["KC_P0", "N0", "number", "Numpad 0", "KC_KP_0"],
  ["KC_PDOT", "N.", "number", "Numpad Dot", "KC_KP_DOT"],
  ["KC_PENT", "N\u21B5", "number", "Numpad Enter", "KC_KP_ENTER"],
  ["KC_PPLS", "N+", "number", "Numpad Plus", "KC_KP_PLUS"],
  ["KC_PMNS", "N-", "number", "Numpad Minus", "KC_KP_MINUS"],
  ["KC_PAST", "N*", "number", "Numpad Asterisk", "KC_KP_ASTERISK"],
  ["KC_PSLS", "N/", "number", "Numpad Slash", "KC_KP_SLASH"],
  ["KC_PEQL", "N=", "number", "Numpad Equal", "KC_KP_EQUAL"],

  // ── Media ──────────────────────────────────────────────
  ["KC_MUTE", "Mute", "media", "Volume Mute"],
  ["KC_VOLU", "Vol+", "media", "Volume Up"],
  ["KC_VOLD", "Vol-", "media", "Volume Down"],
  ["KC_MNXT", "Next", "media", "Media Next", "Next Track"],
  ["KC_MPRV", "Prev", "media", "Media Previous", "Previous Track"],
  ["KC_MSTP", "Stop", "media", "Media Stop"],
  ["KC_MPLY", "Play", "media", "Media Play", "Play/Pause"],
  ["KC_MSEL", "Sel", "media", "Media Select"],
  ["KC_EJCT", "Eject", "media"],
  ["KC_BRIU", "Bri+", "media", "Brightness Up"],
  ["KC_BRID", "Bri-", "media", "Brightness Down"],
  ["KC_BRMU", "Bri+", "media", "Brightness Up Mac"],
  ["KC_BRMD", "Bri-", "media", "Brightness Down Mac"],
  ["KC_MCTL", "MCtrl", "system", "Mission Control"],
  ["KC_LPAD", "LPad", "system", "Launchpad"],

  // ── Mouse ──────────────────────────────────────────────
  ["KC_MS_U", "M\u2191", "mouse", "Mouse Up"],
  ["KC_MS_D", "M\u2193", "mouse", "Mouse Down"],
  ["KC_MS_L", "M\u2190", "mouse", "Mouse Left"],
  ["KC_MS_R", "M\u2192", "mouse", "Mouse Right"],
  ["KC_BTN1", "M1", "mouse", "Mouse Button 1", "Left Click"],
  ["KC_BTN2", "M2", "mouse", "Mouse Button 2", "Right Click"],
  ["KC_BTN3", "M3", "mouse", "Mouse Button 3", "Middle Click"],
  ["KC_BTN4", "M4", "mouse", "Mouse Button 4"],
  ["KC_BTN5", "M5", "mouse", "Mouse Button 5"],
  ["KC_WH_U", "Wh\u2191", "mouse", "Scroll Up", "Mouse Wheel Up"],
  ["KC_WH_D", "Wh\u2193", "mouse", "Scroll Down", "Mouse Wheel Down"],
  ["KC_WH_L", "Wh\u2190", "mouse", "Scroll Left"],
  ["KC_WH_R", "Wh\u2192", "mouse", "Scroll Right"],
  ["KC_ACL0", "Acc0", "mouse", "Mouse Accel 0"],
  ["KC_ACL1", "Acc1", "mouse", "Mouse Accel 1"],
  ["KC_ACL2", "Acc2", "mouse", "Mouse Accel 2"],

  // ── System / Special ───────────────────────────────────
  ["KC_PSCR", "PrtSc", "system", "Print Screen", "KC_PRINT_SCREEN"],
  ["KC_SCRL", "ScrLk", "system", "Scroll Lock", "KC_SCROLL_LOCK", "KC_SLCK"],
  ["KC_PAUS", "Pause", "system", "Pause Break", "KC_PAUSE", "KC_BRK"],
  ["KC_APP", "Menu", "system", "Application", "Context Menu"],
  ["KC_PWR", "Power", "system", "Power"],
  ["KC_SLEP", "Sleep", "system"],
  ["KC_WAKE", "Wake", "system"],
  ["QK_BOOT", "Boot", "system", "Reset", "Bootloader", "QK_BOOTLOADER", "RESET"],
  ["DB_TOGG", "Debug", "system", "Debug Toggle"],
  ["EE_CLR", "EEClr", "system", "EEPROM Clear"],

  // ── Transparent / None ─────────────────────────────────
  ["KC_TRNS", "\u25BD", "transparent", "Trans", "Transparent", "_______"],
  ["KC_NO", "\u2205", "none", "No", "Nothing", "XXXXXXX"],
];

/** All known keycodes as KeycodeDefinition objects */
export const KEYCODES: KeycodeDefinition[] = raw.map(([code, label, category, ...aliases]) => ({
  code,
  label,
  category,
  aliases,
}));
