// Vendored from zmkfirmware/zmk (dt-bindings/zmk/keys.h)
// Source: https://github.com/zmkfirmware/zmk
// License: MIT
//
// Maps ZMK keycode names to display labels.

/** ZMK key name → display label */
export const ZMK_LABELS: Record<string, string> = {
  SYSTEM_POWER: "System Power",
  SYS_PWR: "Sys Pwr",
  SYSTEM_SLEEP: "System Sleep",
  SYS_SLEEP: "Sys Sleep",
  SYSTEM_WAKE_UP: "System Wake Up",
  SYS_WAKE: "Sys Wake",
  A: "A",
  B: "B",
  C: "C",
  D: "D",
  E: "E",
  F: "F",
  G: "G",
  H: "H",
  I: "I",
  J: "J",
  K: "K",
  L: "L",
  M: "M",
  N: "N",
  O: "O",
  P: "P",
  Q: "Q",
  R: "R",
  S: "S",
  T: "T",
  U: "U",
  V: "V",
  W: "W",
  X: "X",
  Y: "Y",
  Z: "Z",
  NUMBER_1: "1",
  N1: "N1",
  NUM_1: "Num 1",
  EXCLAMATION: "! (Exclamation)",
  EXCL: "Excl",
  BANG: "Bang",
  NUMBER_2: "2",
  N2: "N2",
  NUM_2: "Num 2",
  AT_SIGN: "@ (At sign)",
  AT: "AT",
  ATSN: "Atsn",
  NUMBER_3: "3",
  N3: "N3",
  NUM_3: "Num 3",
  HASH: "# (Hash/Number)",
  POUND: "Pound",
  NUMBER_4: "4",
  N4: "N4",
  NUM_4: "Num 4",
  DOLLAR: "$ (Dollar)",
  DLLR: "Dllr",
  NUMBER_5: "5",
  N5: "N5",
  NUM_5: "Num 5",
  PERCENT: "% (Percent)",
  PRCNT: "Prcnt",
  PRCT: "Prct",
  NUMBER_6: "6",
  N6: "N6",
  NUM_6: "Num 6",
  CARET: "^ (Caret)",
  CRRT: "Crrt",
  NUMBER_7: "7",
  N7: "N7",
  NUM_7: "Num 7",
  AMPERSAND: "& (Ampersand)",
  AMPS: "Amps",
  NUMBER_8: "8",
  N8: "N8",
  NUM_8: "Num 8",
  ASTERISK: "* (Asterisk)",
  ASTRK: "Astrk",
  STAR: "Star",
  NUMBER_9: "9",
  N9: "N9",
  NUM_9: "Num 9",
  LEFT_PARENTHESIS: "Left Parenthesis",
  LPAR: "Lpar",
  LPRN: "Lprn",
  NUMBER_0: "0",
  N0: "N0",
  NUM_0: "Num 0",
  RIGHT_PARENTHESIS: "Right Parenthesis",
  RPAR: "Rpar",
  RPRN: "Rprn",
  RETURN: "Return (Enter)",
  ENTER: "Enter",
  RET: "RET",
  ESCAPE: "Escape",
  ESC: "ESC",
  BACKSPACE: "Backspace",
  BSPC: "Bspc",
  BKSP: "Bksp",
  TAB: "TAB",
  SPACE: "Space",
  SPC: "SPC",
  MINUS: "-",
  UNDERSCORE: "_ (Underscore)",
  UNDER: "Under",
  EQUAL: "=",
  EQL: "EQL",
  PLUS: "+ (Plus)",
  LEFT_BRACKET: "[",
  LBKT: "Lbkt",
  LEFT_BRACE: "{ (Left Brace)",
  LBRC: "Lbrc",
  LCUR: "Lcur",
  RIGHT_BRACKET: "]",
  RBKT: "Rbkt",
  RIGHT_BRACE: "} (Right Brace)",
  RBRC: "Rbrc",
  RCUR: "Rcur",
  BACKSLASH: "\\",
  BSLH: "Bslh",
  PIPE: "| (Pipe)",
  NON_US_HASH: "Non-US #",
  NUHS: "Nuhs",
  TILDE2: "~ (Tilde)",
  SEMICOLON: ";",
  SEMI: "Semi",
  SCLN: "Scln",
  COLON: ": (Colon)",
  COLN: "Coln",
  SINGLE_QUOTE: "'",
  SQT: "SQT",
  APOSTROPHE: "Apostrophe",
  APOS: "Apos",
  QUOT: "Quot",
  DOUBLE_QUOTES: '" (Quote)',
  DQT: "DQT",
  GRAVE: "`",
  GRAV: "Grav",
  TILDE: "~ (Tilde)",
  TILD: "Tild",
  COMMA: ",",
  CMMA: "Cmma",
  LESS_THAN: "< (Less Than)",
  LT: "LT",
  LABT: "Labt",
  PERIOD: ".",
  DOT: "DOT",
  GREATER_THAN: "Greater Than",
  GT: "GT",
  RABT: "Rabt",
  SLASH: "/",
  FSLH: "Fslh",
  QUESTION: "? (Question)",
  QMARK: "Qmark",
  CAPSLOCK: "Caps Lock",
  CAPS: "Caps",
  CLCK: "Clck",
  F1: "F1",
  F2: "F2",
  F3: "F3",
  F4: "F4",
  F5: "F5",
  F6: "F6",
  F7: "F7",
  F8: "F8",
  F9: "F9",
  F10: "F10",
  F11: "F11",
  F12: "F12",
  PRINTSCREEN: "Print Screen",
  PSCRN: "Pscrn",
  PRSC: "Prsc",
  SCROLLLOCK: "Scroll Lock",
  SLCK: "Slck",
  SCLK: "Sclk",
  PAUSE_BREAK: "Pause/Break",
  PAUS: "Paus",
  INSERT: "Insert",
  INS: "INS",
  HOME: "Home",
  PAGE_UP: "Page Up",
  PG_UP: "Pg Up",
  PGUP: "Pgup",
  DELETE: "Delete",
  DEL: "DEL",
  END: "END",
  PAGE_DOWN: "Page Down",
  PG_DN: "Pg Dn",
  PGDN: "Pgdn",
  RIGHT_ARROW: "Right Arrow",
  RIGHT: "Right",
  RARW: "Rarw",
  LEFT_ARROW: "Left Arrow",
  LEFT: "Left",
  LARW: "Larw",
  DOWN_ARROW: "Down Arrow",
  DOWN: "Down",
  DARW: "Darw",
  UP_ARROW: "Up Arrow",
  UP: "UP",
  UARW: "Uarw",
  KP_NUMLOCK: "NNumlock",
  KP_NUM: "NNum",
  KP_NLCK: "NNlck",
  CLEAR2: "NClear",
  KP_DIVIDE: "NDivide",
  KP_SLASH: "NSlash",
  KDIV: "Kdiv",
  KP_MULTIPLY: "NMultiply",
  KP_ASTERISK: "NAsterisk",
  KMLT: "Kmlt",
  KP_MINUS: "NMinus",
  KP_SUBTRACT: "NSubtract",
  KMIN: "Kmin",
  KP_PLUS: "NPlus",
  KPLS: "Kpls",
  KP_ENTER: "NEnter",
  KP_NUMBER_1: "NNumber 1",
  KP_N1: "NN1",
  KP_NUMBER_2: "NNumber 2",
  KP_N2: "NN2",
  KP_NUMBER_3: "NNumber 3",
  KP_N3: "NN3",
  KP_NUMBER_4: "NNumber 4",
  KP_N4: "NN4",
  KP_NUMBER_5: "NNumber 5",
  KP_N5: "NN5",
  KP_NUMBER_6: "NNumber 6",
  KP_N6: "NN6",
  KP_NUMBER_7: "NNumber 7",
  KP_N7: "NN7",
  KP_NUMBER_8: "NNumber 8",
  KP_N8: "NN8",
  KP_NUMBER_9: "NNumber 9",
  KP_N9: "NN9",
  KP_NUMBER_0: "NNumber 0",
  KP_N0: "NN0",
  KP_DOT: "NDot",
  NON_US_BACKSLASH: "Non-US \\",
  NON_US_BSLH: "Non Us Bslh",
  NUBS: "Nubs",
  PIPE2: "Pipe",
  K_APPLICATION: "K Application",
  K_APP: "K App",
  K_CONTEXT_MENU: "K Context Menu",
  K_CMENU: "K Cmenu",
  GUI: "GUI",
  K_POWER: "Power",
  K_PWR: "K Pwr",
  KP_EQUAL: "NEqual",
  F13: "F13",
  F14: "F14",
  F15: "F15",
  F16: "F16",
  F17: "F17",
  F18: "F18",
  F19: "F19",
  F20: "F20",
  F21: "F21",
  F22: "F22",
  F23: "F23",
  F24: "F24",
  K_EXECUTE: "Execute",
  K_EXEC: "K Exec",
  K_HELP: "Help",
  K_MENU: "Menu",
  K_SELECT: "Select",
  K_STOP: "Stop",
  K_AGAIN: "Again",
  K_REDO: "K Redo",
  K_UNDO: "Undo",
  UNDO: "Undo",
  K_CUT: "Cut",
  CUT: "CUT",
  K_COPY: "Copy",
  COPY: "Copy",
  K_PASTE: "Paste",
  PSTE: "Pste",
  K_FIND: "Find",
  K_MUTE: "Mute",
  K_VOLUME_UP: "Volume Up",
  K_VOL_UP: "K Vol Up",
  VOLU: "Volu",
  K_VOLUME_DOWN: "Volume Down",
  K_VOL_DN: "K Vol Dn",
  VOLD: "Vold",
  LOCKING_CAPS: "Locking Caps",
  LCAPS: "Lcaps",
  LOCKING_NUM: "Locking Num",
  LNLCK: "Lnlck",
  LOCKING_SCROLL: "Locking Scroll",
  LSLCK: "Lslck",
  KP_COMMA: "NComma",
  KP_EQUAL_AS400: "NEqual As400",
  INTERNATIONAL_1: "International 1",
  INT1: "Int1",
  INT_RO: "Int Ro",
  INTERNATIONAL_2: "International 2",
  INT2: "Int2",
  INT_KATAKANAHIRAGANA: "Int Katakanahiragana",
  INT_KANA: "Int Kana",
  INTERNATIONAL_3: "International 3",
  INT3: "Int3",
  INT_YEN: "Int Yen",
  INTERNATIONAL_4: "International 4",
  INT4: "Int4",
  INT_HENKAN: "Int Henkan",
  INTERNATIONAL_5: "International 5",
  INT5: "Int5",
  INT_MUHENKAN: "Int Muhenkan",
  INTERNATIONAL_6: "International 6",
  INT6: "Int6",
  INT_KPJPCOMMA: "Int Kpjpcomma",
  INTERNATIONAL_7: "International 7",
  INT7: "Int7",
  INTERNATIONAL_8: "International 8",
  INT8: "Int8",
  INTERNATIONAL_9: "International 9",
  INT9: "Int9",
  LANGUAGE_1: "Language 1",
  LANG1: "Lang1",
  LANG_HANGEUL: "Lang Hangeul",
  LANGUAGE_2: "Language 2",
  LANG2: "Lang2",
  LANG_HANJA: "Lang Hanja",
  LANGUAGE_3: "Language 3",
  LANG3: "Lang3",
  LANG_KATAKANA: "Lang Katakana",
  LANGUAGE_4: "Language 4",
  LANG4: "Lang4",
  LANG_HIRAGANA: "Lang Hiragana",
  LANGUAGE_5: "Language 5",
  LANG5: "Lang5",
  LANG_ZENKAKUHANKAKU: "Lang Zenkakuhankaku",
  LANGUAGE_6: "Language 6",
  LANG6: "Lang6",
  LANGUAGE_7: "Language 7",
  LANG7: "Lang7",
  LANGUAGE_8: "Language 8",
  LANG8: "Lang8",
  LANGUAGE_9: "Language 9",
  LANG9: "Lang9",
  ALT_ERASE: "Alternate Erase",
  SYSREQ: "Sysreq",
  ATTENTION: "Attention",
  K_CANCEL: "Cancel",
  CLEAR: "Clear",
  PRIOR: "Prior",
  RETURN2: "Return",
  RET2: "Ret2",
  SEPARATOR: "Separator",
  OUT: "OUT",
  OPER: "Oper",
  CLEAR_AGAIN: "Clear/Again",
  CRSEL: "CrSel/Props",
  EXSEL: "ExSel",
  CURU: "Currency Unit",
  KP_LEFT_PARENTHESIS: "NLeft Parenthesis",
  KP_LPAR: "NLpar",
  KP_RIGHT_PARENTHESIS: "NRight Parenthesis",
  KP_RPAR: "NRpar",
  KSPC: "NSpace",
  KP_CLEAR: "NClear",
  LEFT_CONTROL: "Left Control",
  LCTRL: "Lctrl",
  LCTL: "Lctl",
  LEFT_SHIFT: "Left Shift",
  LSHIFT: "Lshift",
  LSHFT: "Lshft",
  LSFT: "Lsft",
  LEFT_ALT: "Left Alt",
  LALT: "Lalt",
  LEFT_GUI: "Left Gui",
  LGUI: "Lgui",
  LEFT_WIN: "Left Win",
  LWIN: "Lwin",
  LEFT_COMMAND: "Left Command",
  LCMD: "Lcmd",
  LEFT_META: "Left Meta",
  LMETA: "Lmeta",
  RIGHT_CONTROL: "Right Control",
  RCTRL: "Rctrl",
  RCTL: "Rctl",
  RIGHT_SHIFT: "Right Shift",
  RSHIFT: "Rshift",
  RSHFT: "Rshft",
  RSFT: "Rsft",
  RIGHT_ALT: "Right Alt",
  RALT: "Ralt",
  RIGHT_GUI: "Right Gui",
  RGUI: "Rgui",
  RIGHT_WIN: "Right Win",
  RWIN: "Rwin",
  RIGHT_COMMAND: "Right Command",
  RCMD: "Rcmd",
  RIGHT_META: "Right Meta",
  RMETA: "Rmeta",
  K_PLAY_PAUSE: "Play/Pause",
  K_PP: "K Pp",
  K_STOP2: "Stop",
  K_PREVIOUS: "Previous",
  K_PREV: "K Prev",
  K_NEXT: "Next",
  K_EJECT: "Eject",
  K_VOLUME_UP2: "Volume Up",
  K_VOL_UP2: "K Vol Up2",
  K_VOLUME_DOWN2: "Volume Down",
  K_VOL_DN2: "K Vol Dn2",
  K_MUTE2: "Mute",
  K_WWW: "WWW",
  K_BACK: "Back",
  K_FORWARD: "Forward",
  K_STOP3: "Stop",
  K_FIND2: "Find",
  K_SCROLL_UP: "Scroll Up",
  K_SCROLL_DOWN: "Scroll Down",
  K_EDIT: "Edit",
  K_SLEEP: "Sleep",
  K_LOCK: "Lock",
  K_SCREENSAVER: "K Screensaver",
  K_COFFEE: "K Coffee",
  K_REFRESH: "Refresh",
  K_CALCULATOR: "Calculator",
  K_CALC: "K Calc",
  C_POWER: "Consumer Power",
  C_PWR: "C Pwr",
  C_RESET: "Consumer Reset",
  C_SLEEP: "Consumer Sleep",
  C_SLEEP_MODE: "C Sleep Mode",
  C_MENU: "Consumer Menu",
  C_MENU_PICK: "C Menu Pick",
  C_MENU_SELECT: "C Menu Select",
  C_MENU_UP: "C Menu Up",
  C_MENU_DOWN: "C Menu Down",
  C_MENU_LEFT: "C Menu Left",
  C_MENU_RIGHT: "C Menu Right",
  C_MENU_ESCAPE: "C Menu Escape",
  C_MENU_ESC: "C Menu Esc",
  C_MENU_INCREASE: "C Menu Increase",
  C_MENU_INC: "C Menu Inc",
  C_MENU_DECREASE: "C Menu Decrease",
  C_MENU_DEC: "C Menu Dec",
  C_DATA_ON_SCREEN: "C Data On Screen",
  C_CAPTIONS: "C Captions",
  C_SUBTITLES: "C Subtitles",
  C_SNAPSHOT: "C Snapshot",
  C_PIP: "C Pip",
  C_RED_BUTTON: "C Red Button",
  C_RED: "C Red",
  C_GREEN_BUTTON: "C Green Button",
  C_GREEN: "C Green",
  C_BLUE_BUTTON: "C Blue Button",
  C_BLUE: "C Blue",
  C_YELLOW_BUTTON: "C Yellow Button",
  C_YELLOW: "C Yellow",
  C_ASPECT: "Consumer Aspect",
  C_BRIGHTNESS_INC: "C Brightness Inc",
  C_BRI_INC: "C Bri Inc",
  C_BRI_UP: "C Bri Up",
  C_BRIGHTNESS_DEC: "C Brightness Dec",
  C_BRI_DEC: "C Bri Dec",
  C_BRI_DN: "C Bri Dn",
  C_BACKLIGHT_TOGGLE: "C Backlight Toggle",
  C_BKLT_TOG: "C Bklt Tog",
  C_BRIGHTNESS_MINIMUM: "C Brightness Minimum",
  C_BRI_MIN: "C Bri Min",
  C_BRIGHTNESS_MAXIMUM: "C Brightness Maximum",
  C_BRI_MAX: "C Bri Max",
  C_BRIGHTNESS_AUTO: "C Brightness Auto",
  C_BRI_AUTO: "C Bri Auto",
  C_MEDIA_STEP: "C Media Step",
  C_MODE_STEP: "C Mode Step",
  C_RECALL_LAST: "C Recall Last",
  C_CHAN_LAST: "C Chan Last",
  C_MEDIA_COMPUTER: "C Media Computer",
  C_MEDIA_TV: "C Media Tv",
  C_MEDIA_WWW: "C Media Www",
  C_MEDIA_DVD: "C Media Dvd",
  C_MEDIA_PHONE: "C Media Phone",
  C_MEDIA_GUIDE: "C Media Guide",
  C_MEDIA_VIDEOPHONE: "C Media Videophone",
  C_MEDIA_GAMES: "C Media Games",
  C_MEDIA_MESSAGES: "C Media Messages",
  C_MEDIA_CD: "C Media Cd",
  C_MEDIA_VCR: "C Media Vcr",
  C_MEDIA_TUNER: "C Media Tuner",
  C_QUIT: "Consumer Quit",
  C_HELP: "Consumer Help",
  C_MEDIA_TAPE: "C Media Tape",
  C_MEDIA_CABLE: "C Media Cable",
  C_MEDIA_SATELLITE: "C Media Satellite",
  C_MEDIA_HOME: "C Media Home",
  C_CHANNEL_INC: "C Channel Inc",
  C_CHAN_INC: "C Chan Inc",
  C_CHANNEL_DEC: "C Channel Dec",
  C_CHAN_DEC: "C Chan Dec",
  C_MEDIA_VCR_PLUS: "C Media Vcr Plus",
  C_PLAY: "Consumer Play",
  C_PAUSE: "Consumer Pause",
  C_RECORD: "Consumer Record",
  C_REC: "C Rec",
  C_FAST_FORWARD: "C Fast Forward",
  C_FF: "C Ff",
  C_REWIND: "Consumer Rewind",
  C_RW: "C Rw",
  C_NEXT: "C Next",
  M_NEXT: "M Next",
  C_PREVIOUS: "C Previous",
  C_PREV: "C Prev",
  M_PREV: "M Prev",
  C_STOP: "Consumer Stop",
  M_STOP: "M Stop",
  C_EJECT: "Consumer Eject",
  M_EJCT: "M Ejct",
  C_RANDOM_PLAY: "C Random Play",
  C_SHUFFLE: "C Shuffle",
  C_REPEAT: "Consumer Repeat",
  C_SLOW_TRACKING: "C Slow Tracking",
  C_SLOW2: "C Slow2",
  C_STOP_EJECT: "C Stop Eject",
  C_PLAY_PAUSE: "C Play Pause",
  C_PP: "C Pp",
  M_PLAY: "M Play",
  C_VOICE_COMMAND: "C Voice Command",
  C_MUTE: "Consumer Mute",
  M_MUTE: "M Mute",
  C_BASS_BOOST: "C Bass Boost",
  C_VOLUME_UP: "C Volume Up",
  C_VOL_UP: "C Vol Up",
  M_VOLU: "M Volu",
  C_VOLUME_DOWN: "C Volume Down",
  C_VOL_DN: "C Vol Dn",
  M_VOLD: "M Vold",
  C_SLOW: "Consumer Slow",
  C_ALTERNATE_AUDIO_INCREMENT: "C Alternate Audio Increment",
  C_ALT_AUDIO_INC: "C Alt Audio Inc",
  C_AL_CCC: "C Al Ccc",
  C_AL_WORD: "C Al Word",
  C_AL_TEXT_EDITOR: "C Al Text Editor",
  C_AL_SPREADSHEET: "C Al Spreadsheet",
  C_AL_SHEET: "C Al Sheet",
  C_AL_GRAPHICS_EDITOR: "C Al Graphics Editor",
  C_AL_PRESENTATION: "C Al Presentation",
  C_AL_DATABASE: "C Al Database",
  C_AL_DB: "C Al Db",
  C_AL_EMAIL: "C Al Email",
  C_AL_MAIL: "C Al Mail",
  C_AL_NEWS: "C Al News",
  C_AL_VOICEMAIL: "C Al Voicemail",
  C_AL_CONTACTS: "C Al Contacts",
  C_AL_ADDRESS_BOOK: "C Al Address Book",
  C_AL_CALENDAR: "C Al Calendar",
  C_AL_CAL: "C Al Cal",
  C_AL_TASK_MANAGER: "C Al Task Manager",
  C_AL_JOURNAL: "C Al Journal",
  C_AL_FINANCE: "C Al Finance",
  C_AL_CALCULATOR: "C Al Calculator",
  C_AL_CALC: "C Al Calc",
  C_AL_AV_CAPTURE_PLAYBACK: "C Al Av Capture Playback",
  C_AL_MY_COMPUTER: "C Al My Computer",
  C_AL_WWW: "C Al Www",
  C_AL_NETWORK_CHAT: "C Al Network Chat",
  C_AL_CHAT: "C Al Chat",
  C_AL_LOGOFF: "C Al Logoff",
  C_AL_LOCK: "C Al Lock",
  C_AL_SCREENSAVER: "C Al Screensaver",
  C_AL_COFFEE: "C Al Coffee",
  C_AL_CONTROL_PANEL: "C Al Control Panel",
  C_AL_SELECT_TASK: "C Al Select Task",
  C_AL_NEXT_TASK: "C Al Next Task",
  C_AL_PREVIOUS_TASK: "C Al Previous Task",
  C_AL_PREV_TASK: "C Al Prev Task",
  C_AL_HELP: "C Al Help",
  C_AL_DOCUMENTS: "C Al Documents",
  C_AL_DOCS: "C Al Docs",
  C_AL_SPELLCHECK: "C Al Spellcheck",
  C_AL_SPELL: "C Al Spell",
  C_AL_KEYBOARD_LAYOUT: "C Al Keyboard Layout",
  C_AL_SCREEN_SAVER: "C Al Screen Saver",
  C_AL_FILE_BROWSER: "C Al File Browser",
  C_AL_FILES: "C Al Files",
  C_AL_IMAGE_BROWSER: "C Al Image Browser",
  C_AL_IMAGES: "C Al Images",
  C_AL_AUDIO_BROWSER: "C Al Audio Browser",
  C_AL_AUDIO: "C Al Audio",
  C_AL_MUSIC: "C Al Music",
  C_AL_MOVIE_BROWSER: "C Al Movie Browser",
  C_AL_MOVIES: "C Al Movies",
  C_AL_INSTANT_MESSAGING: "C Al Instant Messaging",
  C_AL_IM: "C Al Im",
  C_AL_OEM_FEATURES: "C Al Oem Features",
  C_AL_TIPS: "C Al Tips",
  C_AL_TUTORIAL: "C Al Tutorial",
  C_AC_NEW: "Consumer AC New",
  C_AC_OPEN: "C Ac Open",
  C_AC_CLOSE: "C Ac Close",
  C_AC_EXIT: "C Ac Exit",
  C_AC_SAVE: "C Ac Save",
  C_AC_PRINT: "C Ac Print",
  C_AC_PROPERTIES: "C Ac Properties",
  C_AC_PROPS: "C Ac Props",
  C_AC_UNDO: "C Ac Undo",
  C_AC_COPY: "C Ac Copy",
  C_AC_CUT: "Consumer AC Cut",
  C_AC_PASTE: "C Ac Paste",
  C_AC_FIND: "C Ac Find",
  C_AC_SEARCH: "C Ac Search",
  C_AC_GOTO: "C Ac Goto",
  C_AC_HOME: "C Ac Home",
  C_AC_BACK: "C Ac Back",
  C_AC_FORWARD: "C Ac Forward",
  C_AC_STOP: "C Ac Stop",
  C_AC_REFRESH: "C Ac Refresh",
  C_AC_BOOKMARKS: "C Ac Bookmarks",
  C_AC_FAVORITES: "C Ac Favorites",
  C_AC_FAVOURITES: "C Ac Favourites",
  C_AC_ZOOM_IN: "C Ac Zoom In",
  C_AC_ZOOM_OUT: "C Ac Zoom Out",
  C_AC_ZOOM: "C Ac Zoom",
  C_AC_VIEW_TOGGLE: "C Ac View Toggle",
  C_AC_SCROLL_UP: "C Ac Scroll Up",
  C_AC_SCROLL_DOWN: "C Ac Scroll Down",
  C_AC_EDIT: "C Ac Edit",
  C_AC_CANCEL: "C Ac Cancel",
  C_AC_INSERT: "C Ac Insert",
  C_AC_INS: "C Ac Ins",
  C_AC_DEL: "C Ac Del",
  C_AC_REDO: "C Ac Redo",
  C_AC_REPLY: "C Ac Reply",
  C_AC_FORWARD_MAIL: "C Ac Forward Mail",
  C_AC_SEND: "C Ac Send",
  C_AC_DESKTOP_SHOW_ALL_WINDOWS: "C Ac Desktop Show All Windows",
  C_AC_DESKTOP_SHOW_ALL_APPLICATIONS: "C Ac Desktop Show All Applications",
  C_KEYBOARD_INPUT_ASSIST_PREVIOUS: "C Keyboard Input Assist Previous",
  C_KBIA_PREV: "C Kbia Prev",
  C_KEYBOARD_INPUT_ASSIST_NEXT: "C Keyboard Input Assist Next",
  C_KBIA_NEXT: "C Kbia Next",
  C_KEYBOARD_INPUT_ASSIST_PREVIOUS_GROUP:
    "C Keyboard Input Assist Previous Group",
  C_KBIA_PREV_GRP: "C Kbia Prev Grp",
  C_KEYBOARD_INPUT_ASSIST_NEXT_GROUP: "C Keyboard Input Assist Next Group",
  C_KBIA_NEXT_GRP: "C Kbia Next Grp",
  C_KEYBOARD_INPUT_ASSIST_ACCEPT: "C Keyboard Input Assist Accept",
  C_KBIA_ACCEPT: "C Kbia Accept",
  C_KEYBOARD_INPUT_ASSIST_CANCEL: "C Keyboard Input Assist Cancel",
  C_KBIA_CANCEL: "C Kbia Cancel",
  C_AC_NEXT_KEYBOARD_LAYOUT_SELECT: "Apple Globe key",
  GLOBE: "Globe",
};
