// Vendored from vial-kb/vial-gui (keycodes_v6.py + keycodes.py)
// Source: https://github.com/vial-kb/vial-gui
// License: GPL-2.0-or-later
//
// Do not edit manually.

/** QMK keycode name → display label (from Vial GUI) */
export const VIAL_LABELS: Record<string, string> = {
  "KC_TRNS": "Trans",
  "KC_TRANSPARENT": "Trans",
  "KC_NUMLOCK": "Num Lock",
  "num lock": "Num Lock",
  "KC_KP_SLASH": "/",
  "KC_PSLS": "/",
  "KC_KP_ASTERISK": "*",
  "KC_PAST": "*",
  "KC_KP_MINUS": "-",
  "KC_PMNS": "-",
  "KC_KP_PLUS": "+",
  "KC_PPLS": "+",
  "KC_KP_ENTER": "Num Enter",
  "KC_PENT": "Num Enter",
  "KC_KP_1": "1",
  "KC_P1": "1",
  "KC_KP_2": "2",
  "KC_P2": "2",
  "KC_KP_3": "3",
  "KC_P3": "3",
  "KC_KP_4": "4",
  "KC_P4": "4",
  "KC_KP_5": "5",
  "KC_P5": "5",
  "KC_KP_6": "6",
  "KC_P6": "6",
  "KC_KP_7": "7",
  "KC_P7": "7",
  "KC_KP_8": "8",
  "KC_P8": "8",
  "KC_KP_9": "9",
  "KC_P9": "9",
  "KC_KP_0": "0",
  "KC_P0": "0",
  "KC_KP_DOT": ".",
  "KC_PDOT": ".",
  "KC_KP_EQUAL": "=",
  "KC_PEQL": "=",
  "KC_KP_COMMA": ",",
  "KC_PCMM": ",",
  "KC_PSCREEN": "Print Screen",
  "KC_PSCR": "Print Screen",
  "KC_SCROLLLOCK": "Scroll Lock",
  "scroll lock": "Scroll Lock",
  "KC_PAUSE": "Pause",
  "pause": "Pause",
  "break": "Pause",
  "KC_INSERT": "Insert",
  "insert": "Insert",
  "KC_HOME": "Home",
  "home": "Home",
  "KC_PGUP": "Page Up",
  "page up": "Page Up",
  "KC_DELETE": "Del",
  "delete": "Del",
  "KC_END": "End",
  "end": "End",
  "KC_PGDOWN": "Page Down",
  "page down": "Page Down",
  "KC_RIGHT": "Right",
  "right": "Right",
  "KC_LEFT": "Left",
  "left": "Left",
  "KC_DOWN": "Down",
  "down": "Down",
  "KC_UP": "Up",
  "up": "Up",
  "KC_A": "A",
  "a": "A",
  "KC_B": "B",
  "b": "B",
  "KC_C": "C",
  "c": "C",
  "KC_D": "D",
  "d": "D",
  "KC_E": "E",
  "e": "E",
  "KC_F": "F",
  "f": "F",
  "KC_G": "G",
  "g": "G",
  "KC_H": "H",
  "h": "H",
  "KC_I": "I",
  "i": "I",
  "KC_J": "J",
  "j": "J",
  "KC_K": "K",
  "k": "K",
  "KC_L": "L",
  "l": "L",
  "KC_M": "M",
  "m": "M",
  "KC_N": "N",
  "n": "N",
  "KC_O": "O",
  "o": "O",
  "KC_P": "P",
  "p": "P",
  "KC_Q": "Q",
  "q": "Q",
  "KC_R": "R",
  "r": "R",
  "KC_S": "S",
  "s": "S",
  "KC_T": "T",
  "t": "T",
  "KC_U": "U",
  "u": "U",
  "KC_V": "V",
  "v": "V",
  "KC_W": "W",
  "w": "W",
  "KC_X": "X",
  "x": "X",
  "KC_Y": "Y",
  "y": "Y",
  "KC_Z": "Z",
  "z": "Z",
  "KC_1": "! 1",
  "1": "! 1",
  "KC_2": "@ 2",
  "2": "@ 2",
  "KC_3": "# 3",
  "3": "# 3",
  "KC_4": "$ 4",
  "4": "$ 4",
  "KC_5": "% 5",
  "5": "% 5",
  "KC_6": "^ 6",
  "6": "^ 6",
  "KC_7": "& 7",
  "7": "& 7",
  "KC_8": "* 8",
  "8": "* 8",
  "KC_9": "( 9",
  "9": "( 9",
  "KC_0": ") 0",
  "0": ") 0",
  "KC_ENTER": "Enter",
  "enter": "Enter",
  "KC_ESCAPE": "Esc",
  "esc": "Esc",
  "KC_BSPACE": "Bksp",
  "backspace": "Bksp",
  "KC_TAB": "Tab",
  "tab": "Tab",
  "KC_SPACE": "Space",
  "space": "Space",
  "KC_MINUS": "_ -",
  "-": "_ -",
  "KC_EQUAL": "+ =",
  "=": "+ =",
  "KC_LBRACKET": "{ [",
  "[": "{ [",
  "KC_RBRACKET": "} ]",
  "KC_BSLASH": "| \\\\",
  "\\": "| \\\\",
  "KC_SCOLON": ": ;",
  ";": ": ;",
  "KC_QUOTE": "\\",
  "'": "\\",
  "KC_GRAVE": "~ `",
  "`": "~ `",
  "KC_COMMA": "< ,",
  "KC_DOT": "> .",
  ".": "> .",
  "KC_SLASH": "? /",
  "/": "? /",
  "KC_CAPSLOCK": "Caps Lock",
  "caps lock": "Caps Lock",
  "KC_F1": "F1",
  "f1": "F1",
  "KC_F2": "F2",
  "f2": "F2",
  "KC_F3": "F3",
  "f3": "F3",
  "KC_F4": "F4",
  "f4": "F4",
  "KC_F5": "F5",
  "f5": "F5",
  "KC_F6": "F6",
  "f6": "F6",
  "KC_F7": "F7",
  "f7": "F7",
  "KC_F8": "F8",
  "f8": "F8",
  "KC_F9": "F9",
  "f9": "F9",
  "KC_F10": "F10",
  "f10": "F10",
  "KC_F11": "F11",
  "f11": "F11",
  "KC_F12": "F12",
  "f12": "F12",
  "KC_APPLICATION": "Menu",
  "menu": "Menu",
  "left menu": "Menu",
  "right menu": "Menu",
  "KC_LCTRL": "LCtrl",
  "left ctrl": "LCtrl",
  "ctrl": "LCtrl",
  "KC_LSHIFT": "LShift",
  "left shift": "LShift",
  "shift": "LShift",
  "KC_LALT": "LAlt",
  "alt": "LAlt",
  "KC_LGUI": "LGui",
  "left windows": "LGui",
  "windows": "LGui",
  "KC_RCTRL": "RCtrl",
  "right ctrl": "RCtrl",
  "KC_RSHIFT": "RShift",
  "right shift": "RShift",
  "KC_RALT": "RAlt",
  "KC_ALGR": "RAlt",
  "KC_ROPT": "RAlt",
  "KC_RGUI": "RGui",
  "right windows": "RGui",
  "KC_TILD": "~",
  "KC_EXLM": "!",
  "KC_AT": "@",
  "KC_HASH": "#",
  "KC_DLR": "$",
  "KC_PERC": "%",
  "KC_CIRC": "^",
  "KC_AMPR": "&",
  "KC_ASTR": "*",
  "KC_LPRN": "(",
  "KC_RPRN": ")",
  "KC_UNDS": "_",
  "KC_PLUS": "+",
  "KC_LCBR": "{",
  "KC_RCBR": "}",
  "KC_LT": "<",
  "KC_GT": ">",
  "KC_COLN": ":",
  "KC_PIPE": "|",
  "KC_QUES": "?",
  "KC_NONUS_HASH": "~ #",
  "KC_NUHS": "~ #",
  "KC_NONUS_BSLASH": "| \\\\",
  "KC_NUBS": "| \\\\",
  "KC_RO": "_ \\\\",
  "KC_INT1": "_ \\\\",
  "KC_KANA": "カタカナ ひらがな",
  "KC_INT2": "カタカナ ひらがな",
  "KC_JYEN": "| ¥",
  "KC_INT3": "| ¥",
  "KC_HENK": "変換",
  "KC_INT4": "変換",
  "KC_MHEN": "無変換",
  "KC_INT5": "無変換",
  "KC_LANG1": "한영 かな",
  "KC_HAEN": "한영 かな",
  "KC_LANG2": "漢字 英数",
  "KC_HANJ": "漢字 英数",
  "QK_BOOT": "Boot- loader",
  "RESET": "Boot- loader",
  "QK_REBOOT": "Reboot",
  "QK_CLEAR_EEPROM": "Clear EEPROM",
  "EE_CLR": "Clear EEPROM",
  "OSM(MOD_LSFT)": "OSM LSft",
  "OSM(MOD_LCTL)": "OSM LCtl",
  "OSM(MOD_LALT)": "OSM LAlt",
  "OSM(MOD_LGUI)": "OSM LGUI",
  "OSM(MOD_RSFT)": "OSM RSft",
  "OSM(MOD_RCTL)": "OSM RCtl",
  "OSM(MOD_RALT)": "OSM RAlt",
  "OSM(MOD_RGUI)": "OSM RGUI",
  "OSM(MOD_LCTL|MOD_LSFT)": "OSM CS",
  "OSM(MOD_LCTL|MOD_LALT)": "OSM CA",
  "OSM(MOD_LCTL|MOD_LGUI)": "OSM CG",
  "OSM(MOD_LSFT|MOD_LALT)": "OSM SA",
  "OSM(MOD_LSFT|MOD_LGUI)": "OSM SG",
  "OSM(MOD_LALT|MOD_LGUI)": "OSM AG",
  "OSM(MOD_RCTL|MOD_RSFT)": "OSM RCS",
  "OSM(MOD_RCTL|MOD_RALT)": "OSM RCA",
  "OSM(MOD_RCTL|MOD_RGUI)": "OSM RCG",
  "OSM(MOD_RSFT|MOD_RALT)": "OSM RSA",
  "OSM(MOD_RSFT|MOD_RGUI)": "OSM RSG",
  "OSM(MOD_RALT|MOD_RGUI)": "OSM RAG",
  "OSM(MOD_LCTL|MOD_LSFT|MOD_LGUI)": "OSM CSG",
  "OSM(MOD_LCTL|MOD_LALT|MOD_LGUI)": "OSM CAG",
  "OSM(MOD_LSFT|MOD_LALT|MOD_LGUI)": "OSM SAG",
  "OSM(MOD_RCTL|MOD_RSFT|MOD_RGUI)": "OSM RCSG",
  "OSM(MOD_RCTL|MOD_RALT|MOD_RGUI)": "OSM RCAG",
  "OSM(MOD_RSFT|MOD_RALT|MOD_RGUI)": "OSM RSAG",
  "OSM(MOD_MEH)": "OSM Meh",
  "OSM(MOD_HYPR)": "OSM Hyper",
  "OSM(MOD_RCTL|MOD_RSFT|MOD_RALT)": "OSM RMeh",
  "OSM(MOD_RCTL|MOD_RSFT|MOD_RALT|MOD_RGUI)": "OSM RHyp",
  "LSFT(kc)": "LSft (kc)",
  "LCTL(kc)": "LCtl (kc)",
  "LALT(kc)": "LAlt (kc)",
  "LGUI(kc)": "LGui (kc)",
  "RSFT(kc)": "RSft (kc)",
  "RCTL(kc)": "RCtl (kc)",
  "RALT(kc)": "RAlt (kc)",
  "RGUI(kc)": "RGui (kc)",
  "C_S(kc)": "LCS (kc)",
  "LCS(kc)": "LCS (kc)",
  "LCA(kc)": "LCA (kc)",
  "LCG(kc)": "LCG (kc)",
  "LSA(kc)": "LSA (kc)",
  "LAG(kc)": "LAG (kc)",
  "SGUI(kc)": "LSG (kc)",
  "LSG(kc)": "LSG (kc)",
  "LCAG(kc)": "LCAG (kc)",
  "RCG(kc)": "RCG (kc)",
  "MEH(kc)": "Meh (kc)",
  "HYPR(kc)": "Hyper (kc)",
  "LSFT_T(kc)": "LSft_T (kc)",
  "LCTL_T(kc)": "LCtl_T (kc)",
  "LALT_T(kc)": "LAlt_T (kc)",
  "LGUI_T(kc)": "LGui_T (kc)",
  "RSFT_T(kc)": "RSft_T (kc)",
  "RCTL_T(kc)": "RCtl_T (kc)",
  "RALT_T(kc)": "RAlt_T (kc)",
  "RGUI_T(kc)": "RGui_T (kc)",
  "C_S_T(kc)": "LCS_T (kc)",
  "LCS_T(kc)": "LCS_T (kc)",
  "LCA_T(kc)": "LCA_T (kc)",
  "LCG_T(kc)": "LCG_T (kc)",
  "LSA_T(kc)": "LSA_T (kc)",
  "LAG_T(kc)": "LAG_T (kc)",
  "SGUI_T(kc)": "LSG_T (kc)",
  "LSG_T(kc)": "LSG_T (kc)",
  "LCAG_T(kc)": "LCAG_T (kc)",
  "RCG_T(kc)": "RCG_T (kc)",
  "RCAG_T(kc)": "RCAG_T (kc)",
  "MEH_T(kc)": "Meh_T (kc)",
  "ALL_T(kc)": "ALL_T (kc)",
  "KC_GESC": "~ Esc",
  "KC_LSPO": "LS (",
  "KC_RSPC": "RS )",
  "KC_LCPO": "LC (",
  "KC_RCPC": "RC )",
  "KC_LAPO": "LA (",
  "KC_RAPC": "RA )",
  "KC_SFTENT": "RS Enter",
  "MAGIC_SWAP_CONTROL_CAPSLOCK": "Swap Ctrl Caps",
  "CL_SWAP": "Swap Ctrl Caps",
  "MAGIC_UNSWAP_CONTROL_CAPSLOCK": "Unswap Ctrl Caps",
  "CL_NORM": "Unswap Ctrl Caps",
  "MAGIC_CAPSLOCK_TO_CONTROL": "Caps to Ctrl",
  "CL_CTRL": "Caps to Ctrl",
  "MAGIC_UNCAPSLOCK_TO_CONTROL": "Caps not to Ctrl",
  "CL_CAPS": "Caps not to Ctrl",
  "MAGIC_SWAP_LCTL_LGUI": "Swap LCtl LGui",
  "LCG_SWP": "Swap LCtl LGui",
  "MAGIC_UNSWAP_LCTL_LGUI": "Unswap LCtl LGui",
  "LCG_NRM": "Unswap LCtl LGui",
  "MAGIC_SWAP_RCTL_RGUI": "Swap RCtl RGui",
  "RCG_SWP": "Swap RCtl RGui",
  "MAGIC_UNSWAP_RCTL_RGUI": "Unswap RCtl RGui",
  "RCG_NRM": "Unswap RCtl RGui",
  "MAGIC_SWAP_CTL_GUI": "Swap Ctl Gui",
  "CG_SWAP": "Swap Ctl Gui",
  "MAGIC_UNSWAP_CTL_GUI": "Unswap Ctl Gui",
  "CG_NORM": "Unswap Ctl Gui",
  "MAGIC_TOGGLE_CTL_GUI": "Toggle Ctl Gui",
  "CG_TOGG": "Toggle Ctl Gui",
  "MAGIC_SWAP_LALT_LGUI": "Swap LAlt LGui",
  "LAG_SWP": "Swap LAlt LGui",
  "MAGIC_UNSWAP_LALT_LGUI": "Unswap LAlt LGui",
  "LAG_NRM": "Unswap LAlt LGui",
  "MAGIC_SWAP_RALT_RGUI": "Swap RAlt RGui",
  "RAG_SWP": "Swap RAlt RGui",
  "MAGIC_UNSWAP_RALT_RGUI": "Unswap RAlt RGui",
  "RAG_NRM": "Unswap RAlt RGui",
  "MAGIC_SWAP_ALT_GUI": "Swap Alt Gui",
  "AG_SWAP": "Swap Alt Gui",
  "MAGIC_UNSWAP_ALT_GUI": "Unswap Alt Gui",
  "AG_NORM": "Unswap Alt Gui",
  "MAGIC_TOGGLE_ALT_GUI": "Toggle Alt Gui",
  "AG_TOGG": "Toggle Alt Gui",
  "MAGIC_NO_GUI": "GUI Off",
  "GUI_OFF": "GUI Off",
  "MAGIC_UNNO_GUI": "GUI On",
  "GUI_ON": "GUI On",
  "MAGIC_TOGGLE_GUI": "GUI Toggle",
  "GUI_TOGG": "GUI Toggle",
  "MAGIC_SWAP_GRAVE_ESC": "Swap ` Esc",
  "GE_SWAP": "Swap ` Esc",
  "MAGIC_UNSWAP_GRAVE_ESC": "Unswap ` Esc",
  "GE_NORM": "Unswap ` Esc",
  "MAGIC_SWAP_BACKSLASH_BACKSPACE": "Swap \\\\ BS",
  "BS_SWAP": "Swap \\\\ BS",
  "MAGIC_UNSWAP_BACKSLASH_BACKSPACE": "Unswap \\\\ BS",
  "BS_NORM": "Unswap \\\\ BS",
  "MAGIC_HOST_NKRO": "NKRO On",
  "NK_ON": "NKRO On",
  "MAGIC_UNHOST_NKRO": "NKRO Off",
  "NK_OFF": "NKRO Off",
  "MAGIC_TOGGLE_NKRO": "NKRO Toggle",
  "NK_TOGG": "NKRO Toggle",
  "MAGIC_EE_HANDS_LEFT": "EEH Left",
  "EH_LEFT": "EEH Left",
  "MAGIC_EE_HANDS_RIGHT": "EEH Right",
  "EH_RGHT": "EEH Right",
  "AU_ON": "Audio ON",
  "AU_OFF": "Audio OFF",
  "AU_TOG": "Audio Toggle",
  "CLICKY_TOGGLE": "Clicky Toggle",
  "CK_TOGG": "Clicky Toggle",
  "CLICKY_UP": "Clicky Up",
  "CK_UP": "Clicky Up",
  "CLICKY_DOWN": "Clicky Down",
  "CK_DOWN": "Clicky Down",
  "CLICKY_RESET": "Clicky Reset",
  "CK_RST": "Clicky Reset",
  "MU_ON": "Music On",
  "MU_OFF": "Music Off",
  "MU_TOG": "Music Toggle",
  "MU_MOD": "Music Cycle",
  "HPT_ON": "Haptic On",
  "HPT_OFF": "Haptic Off",
  "HPT_TOG": "Haptic Toggle",
  "HPT_RST": "Haptic Reset",
  "HPT_FBK": "Haptic Feed back",
  "HPT_BUZ": "Haptic Buzz",
  "HPT_MODI": "Haptic Next",
  "HPT_MODD": "Haptic Prev",
  "HPT_CONT": "Haptic Cont.",
  "HPT_CONI": "Haptic +",
  "HPT_COND": "Haptic -",
  "HPT_DWLI": "Haptic Dwell+",
  "HPT_DWLD": "Haptic Dwell-",
  "KC_ASDN": "Auto- shift Down",
  "KC_ASUP": "Auto- shift Up",
  "KC_ASRP": "Auto- shift Report",
  "KC_ASON": "Auto- shift On",
  "KC_ASOFF": "Auto- shift Off",
  "KC_ASTG": "Auto- shift Toggle",
  "CMB_ON": "Combo On",
  "CMB_OFF": "Combo Off",
  "CMB_TOG": "Combo Toggle",
  "QK_CAPS_WORD_TOGGLE": "Caps Word",
  "CW_TOGG": "Caps Word",
  "QK_REPEAT_KEY": "Repeat",
  "QK_REP": "Repeat",
  "QK_ALT_REPEAT_KEY": "Alt Repeat",
  "QK_AREP": "Alt Repeat",
  "BL_TOGG": "BL Toggle",
  "BL_STEP": "BL Cycle",
  "BL_BRTG": "BL Breath",
  "BL_ON": "BL On",
  "BL_OFF": "BL Off",
  "BL_INC": "BL +",
  "BL_DEC": "BL -",
  "RGB_TOG": "RGB Toggle",
  "RGB_MOD": "RGB Mode +",
  "RGB_RMOD": "RGB Mode -",
  "RGB_HUI": "Hue +",
  "RGB_HUD": "Hue -",
  "RGB_SAI": "Sat +",
  "RGB_SAD": "Sat -",
  "RGB_VAI": "Bright +",
  "RGB_VAD": "Bright -",
  "RGB_SPI": "Effect +",
  "RGB_SPD": "Effect -",
  "RGB_M_P": "RGB Mode P",
  "RGB_M_B": "RGB Mode B",
  "RGB_M_R": "RGB Mode R",
  "RGB_M_SW": "RGB Mode SW",
  "RGB_M_SN": "RGB Mode SN",
  "RGB_M_K": "RGB Mode K",
  "RGB_M_X": "RGB Mode X",
  "RGB_M_G": "RGB Mode G",
  "RGB_M_T": "RGB Mode T",
  "RM_ON": "RGBM On",
  "RM_OFF": "RGBM Off",
  "RM_TOGG": "RGBM Togg",
  "RM_NEXT": "RGBM Next",
  "RM_PREV": "RGBM Prev",
  "RM_HUEU": "RGBM Hue +",
  "RM_HUED": "RGBM Hue -",
  "RM_SATU": "RGBM Sat +",
  "RM_SATD": "RGBM Sat -",
  "RM_VALU": "RGBM Bright +",
  "RM_VALD": "RGBM Bright -",
  "RM_SPDU": "RGBM Speed +",
  "RM_SPDD": "RGBM Speed -",
  "KC_F13": "F13",
  "KC_F14": "F14",
  "KC_F15": "F15",
  "KC_F16": "F16",
  "KC_F17": "F17",
  "KC_F18": "F18",
  "KC_F19": "F19",
  "KC_F20": "F20",
  "KC_F21": "F21",
  "KC_F22": "F22",
  "KC_F23": "F23",
  "KC_F24": "F24",
  "KC_PWR": "Power",
  "KC_SYSTEM_POWER": "Power",
  "KC_SLEP": "Sleep",
  "KC_SYSTEM_SLEEP": "Sleep",
  "KC_WAKE": "Wake",
  "KC_SYSTEM_WAKE": "Wake",
  "KC_EXEC": "Exec",
  "KC_EXECUTE": "Exec",
  "KC_HELP": "Help",
  "KC_SLCT": "Select",
  "KC_SELECT": "Select",
  "KC_STOP": "Stop",
  "KC_AGIN": "Again",
  "KC_AGAIN": "Again",
  "KC_UNDO": "Undo",
  "KC_CUT": "Cut",
  "KC_COPY": "Copy",
  "KC_PSTE": "Paste",
  "KC_PASTE": "Paste",
  "KC_FIND": "Find",
  "KC_CALC": "Calc",
  "KC_CALCULATOR": "Calc",
  "KC_MAIL": "Mail",
  "KC_MSEL": "Media Player",
  "KC_MEDIA_SELECT": "Media Player",
  "KC_MYCM": "My PC",
  "KC_MY_COMPUTER": "My PC",
  "KC_WSCH": "Browser Search",
  "KC_WWW_SEARCH": "Browser Search",
  "KC_WHOM": "Browser Home",
  "KC_WWW_HOME": "Browser Home",
  "KC_WBAK": "Browser Back",
  "KC_WWW_BACK": "Browser Back",
  "KC_WFWD": "Browser Forward",
  "KC_WWW_FORWARD": "Browser Forward",
  "KC_WSTP": "Browser Stop",
  "KC_WWW_STOP": "Browser Stop",
  "KC_WREF": "Browser Refresh",
  "KC_WWW_REFRESH": "Browser Refresh",
  "KC_WFAV": "Browser Fav.",
  "KC_WWW_FAVORITES": "Browser Fav.",
  "KC_BRIU": "Bright. Up",
  "KC_BRIGHTNESS_UP": "Bright. Up",
  "KC_BRID": "Bright. Down",
  "KC_BRIGHTNESS_DOWN": "Bright. Down",
  "KC_MPRV": "Media Prev",
  "KC_MEDIA_PREV_TRACK": "Media Prev",
  "KC_MNXT": "Media Next",
  "KC_MEDIA_NEXT_TRACK": "Media Next",
  "KC_MUTE": "Mute",
  "KC_AUDIO_MUTE": "Mute",
  "KC_VOLD": "Vol -",
  "KC_AUDIO_VOL_DOWN": "Vol -",
  "KC_VOLU": "Vol +",
  "KC_AUDIO_VOL_UP": "Vol +",
  "KC__VOLDOWN": "Vol - Alt",
  "KC__VOLUP": "Vol + Alt",
  "KC_MSTP": "Media Stop",
  "KC_MEDIA_STOP": "Media Stop",
  "KC_MPLY": "Media Play",
  "KC_MEDIA_PLAY_PAUSE": "Media Play",
  "KC_MRWD": "Prev Track (macOS)",
  "KC_MEDIA_REWIND": "Prev Track (macOS)",
  "KC_MFFD": "Next Track (macOS)",
  "KC_MEDIA_FAST_FORWARD": "Next Track (macOS)",
  "KC_EJCT": "Eject",
  "KC_MEDIA_EJECT": "Eject",
  "KC_MS_U": "Mouse Up",
  "KC_MS_UP": "Mouse Up",
  "KC_MS_D": "Mouse Down",
  "KC_MS_DOWN": "Mouse Down",
  "KC_MS_L": "Mouse Left",
  "KC_MS_LEFT": "Mouse Left",
  "KC_MS_R": "Mouse Right",
  "KC_MS_RIGHT": "Mouse Right",
  "KC_BTN1": "Mouse 1",
  "KC_MS_BTN1": "Mouse 1",
  "KC_BTN2": "Mouse 2",
  "KC_MS_BTN2": "Mouse 2",
  "KC_BTN3": "Mouse 3",
  "KC_MS_BTN3": "Mouse 3",
  "KC_BTN4": "Mouse 4",
  "KC_MS_BTN4": "Mouse 4",
  "KC_BTN5": "Mouse 5",
  "KC_MS_BTN5": "Mouse 5",
  "KC_WH_U": "Mouse Wheel Up",
  "KC_MS_WH_UP": "Mouse Wheel Up",
  "KC_WH_D": "Mouse Wheel Down",
  "KC_MS_WH_DOWN": "Mouse Wheel Down",
  "KC_WH_L": "Mouse Wheel Left",
  "KC_MS_WH_LEFT": "Mouse Wheel Left",
  "KC_WH_R": "Mouse Wheel Right",
  "KC_MS_WH_RIGHT": "Mouse Wheel Right",
  "KC_ACL0": "Mouse Accel 0",
  "KC_MS_ACCEL0": "Mouse Accel 0",
  "KC_ACL1": "Mouse Accel 1",
  "KC_MS_ACCEL1": "Mouse Accel 1",
  "KC_ACL2": "Mouse Accel 2",
  "KC_MS_ACCEL2": "Mouse Accel 2",
  "KC_LCAP": "Locking Caps",
  "KC_LOCKING_CAPS": "Locking Caps",
  "KC_LNUM": "Locking Num",
  "KC_LOCKING_NUM": "Locking Num",
  "KC_LSCR": "Locking Scroll",
  "KC_LOCKING_SCROLL": "Locking Scroll",
  "DYN_REC_START1": "DM1 Rec",
  "DM_REC1": "DM1 Rec",
  "DYN_REC_START2": "DM2 Rec",
  "DM_REC2": "DM2 Rec",
  "DYN_REC_STOP": "DM Rec Stop",
  "DM_RSTP": "DM Rec Stop",
  "DYN_MACRO_PLAY1": "DM1 Play",
  "DM_PLY1": "DM1 Play",
  "DYN_MACRO_PLAY2": "DM2 Play",
  "DM_PLY2": "DM2 Play",
  "MI_C": "ᴹᴵᴰᴵ C",
  "MI_Cs": "ᴹᴵᴰᴵ C#/Dᵇ",
  "MI_Db": "ᴹᴵᴰᴵ C#/Dᵇ",
  "MI_D": "ᴹᴵᴰᴵ D",
  "MI_Ds": "ᴹᴵᴰᴵ D#/Eᵇ",
  "MI_Eb": "ᴹᴵᴰᴵ D#/Eᵇ",
  "MI_E": "ᴹᴵᴰᴵ E",
  "MI_F": "ᴹᴵᴰᴵ F",
  "MI_Fs": "ᴹᴵᴰᴵ F#/Gᵇ",
  "MI_Gb": "ᴹᴵᴰᴵ F#/Gᵇ",
  "MI_G": "ᴹᴵᴰᴵ G",
  "MI_Gs": "ᴹᴵᴰᴵ G#/Aᵇ",
  "MI_Ab": "ᴹᴵᴰᴵ G#/Aᵇ",
  "MI_A": "ᴹᴵᴰᴵ A",
  "MI_As": "ᴹᴵᴰᴵ A#/Bᵇ",
  "MI_Bb": "ᴹᴵᴰᴵ A#/Bᵇ",
  "MI_B": "ᴹᴵᴰᴵ B",
  "MI_C_1": "ᴹᴵᴰᴵ C₁",
  "MI_Cs_1": "ᴹᴵᴰᴵ C#₁/Dᵇ₁",
  "MI_Db_1": "ᴹᴵᴰᴵ C#₁/Dᵇ₁",
  "MI_D_1": "ᴹᴵᴰᴵ D₁",
  "MI_Ds_1": "ᴹᴵᴰᴵ D#₁/Eᵇ₁",
  "MI_Eb_1": "ᴹᴵᴰᴵ D#₁/Eᵇ₁",
  "MI_E_1": "ᴹᴵᴰᴵ E₁",
  "MI_F_1": "ᴹᴵᴰᴵ F₁",
  "MI_Fs_1": "ᴹᴵᴰᴵ F#₁/Gᵇ₁",
  "MI_Gb_1": "ᴹᴵᴰᴵ F#₁/Gᵇ₁",
  "MI_G_1": "ᴹᴵᴰᴵ G₁",
  "MI_Gs_1": "ᴹᴵᴰᴵ G#₁/Aᵇ₁",
  "MI_Ab_1": "ᴹᴵᴰᴵ G#₁/Aᵇ₁",
  "MI_A_1": "ᴹᴵᴰᴵ A₁",
  "MI_As_1": "ᴹᴵᴰᴵ A#₁/Bᵇ₁",
  "MI_Bb_1": "ᴹᴵᴰᴵ A#₁/Bᵇ₁",
  "MI_B_1": "ᴹᴵᴰᴵ B₁",
  "MI_C_2": "ᴹᴵᴰᴵ C₂",
  "MI_Cs_2": "ᴹᴵᴰᴵ C#₂/Dᵇ₂",
  "MI_Db_2": "ᴹᴵᴰᴵ C#₂/Dᵇ₂",
  "MI_D_2": "ᴹᴵᴰᴵ D₂",
  "MI_Ds_2": "ᴹᴵᴰᴵ D#₂/Eᵇ₂",
  "MI_Eb_2": "ᴹᴵᴰᴵ D#₂/Eᵇ₂",
  "MI_E_2": "ᴹᴵᴰᴵ E₂",
  "MI_F_2": "ᴹᴵᴰᴵ F₂",
  "MI_Fs_2": "ᴹᴵᴰᴵ F#₂/Gᵇ₂",
  "MI_Gb_2": "ᴹᴵᴰᴵ F#₂/Gᵇ₂",
  "MI_G_2": "ᴹᴵᴰᴵ G₂",
  "MI_Gs_2": "ᴹᴵᴰᴵ G#₂/Aᵇ₂",
  "MI_Ab_2": "ᴹᴵᴰᴵ G#₂/Aᵇ₂",
  "MI_A_2": "ᴹᴵᴰᴵ A₂",
  "MI_As_2": "ᴹᴵᴰᴵ A#₂/Bᵇ₂",
  "MI_Bb_2": "ᴹᴵᴰᴵ A#₂/Bᵇ₂",
  "MI_B_2": "ᴹᴵᴰᴵ B₂",
  "MI_C_3": "ᴹᴵᴰᴵ C₃",
  "MI_Cs_3": "ᴹᴵᴰᴵ C#₃/Dᵇ₃",
  "MI_Db_3": "ᴹᴵᴰᴵ C#₃/Dᵇ₃",
  "MI_D_3": "ᴹᴵᴰᴵ D₃",
  "MI_Ds_3": "ᴹᴵᴰᴵ D#₃/Eᵇ₃",
  "MI_Eb_3": "ᴹᴵᴰᴵ D#₃/Eᵇ₃",
  "MI_E_3": "ᴹᴵᴰᴵ E₃",
  "MI_F_3": "ᴹᴵᴰᴵ F₃",
  "MI_Fs_3": "ᴹᴵᴰᴵ F#₃/Gᵇ₃",
  "MI_Gb_3": "ᴹᴵᴰᴵ F#₃/Gᵇ₃",
  "MI_G_3": "ᴹᴵᴰᴵ G₃",
  "MI_Gs_3": "ᴹᴵᴰᴵ G#₃/Aᵇ₃",
  "MI_Ab_3": "ᴹᴵᴰᴵ G#₃/Aᵇ₃",
  "MI_A_3": "ᴹᴵᴰᴵ A₃",
  "MI_As_3": "ᴹᴵᴰᴵ A#₃/Bᵇ₃",
  "MI_Bb_3": "ᴹᴵᴰᴵ A#₃/Bᵇ₃",
  "MI_B_3": "ᴹᴵᴰᴵ B₃",
  "MI_C_4": "ᴹᴵᴰᴵ C₄",
  "MI_Cs_4": "ᴹᴵᴰᴵ C#₄/Dᵇ₄",
  "MI_Db_4": "ᴹᴵᴰᴵ C#₄/Dᵇ₄",
  "MI_D_4": "ᴹᴵᴰᴵ D₄",
  "MI_Ds_4": "ᴹᴵᴰᴵ D#₄/Eᵇ₄",
  "MI_Eb_4": "ᴹᴵᴰᴵ D#₄/Eᵇ₄",
  "MI_E_4": "ᴹᴵᴰᴵ E₄",
  "MI_F_4": "ᴹᴵᴰᴵ F₄",
  "MI_Fs_4": "ᴹᴵᴰᴵ F#₄/Gᵇ₄",
  "MI_Gb_4": "ᴹᴵᴰᴵ F#₄/Gᵇ₄",
  "MI_G_4": "ᴹᴵᴰᴵ G₄",
  "MI_Gs_4": "ᴹᴵᴰᴵ G#₄/Aᵇ₄",
  "MI_Ab_4": "ᴹᴵᴰᴵ G#₄/Aᵇ₄",
  "MI_A_4": "ᴹᴵᴰᴵ A₄",
  "MI_As_4": "ᴹᴵᴰᴵ A#₄/Bᵇ₄",
  "MI_Bb_4": "ᴹᴵᴰᴵ A#₄/Bᵇ₄",
  "MI_B_4": "ᴹᴵᴰᴵ B₄",
  "MI_C_5": "ᴹᴵᴰᴵ C₅",
  "MI_Cs_5": "ᴹᴵᴰᴵ C#₅/Dᵇ₅",
  "MI_Db_5": "ᴹᴵᴰᴵ C#₅/Dᵇ₅",
  "MI_D_5": "ᴹᴵᴰᴵ D₅",
  "MI_Ds_5": "ᴹᴵᴰᴵ D#₅/Eᵇ₅",
  "MI_Eb_5": "ᴹᴵᴰᴵ D#₅/Eᵇ₅",
  "MI_E_5": "ᴹᴵᴰᴵ E₅",
  "MI_F_5": "ᴹᴵᴰᴵ F₅",
  "MI_Fs_5": "ᴹᴵᴰᴵ F#₅/Gᵇ₅",
  "MI_Gb_5": "ᴹᴵᴰᴵ F#₅/Gᵇ₅",
  "MI_G_5": "ᴹᴵᴰᴵ G₅",
  "MI_Gs_5": "ᴹᴵᴰᴵ G#₅/Aᵇ₅",
  "MI_Ab_5": "ᴹᴵᴰᴵ G#₅/Aᵇ₅",
  "MI_A_5": "ᴹᴵᴰᴵ A₅",
  "MI_As_5": "ᴹᴵᴰᴵ A#₅/Bᵇ₅",
  "MI_Bb_5": "ᴹᴵᴰᴵ A#₅/Bᵇ₅",
  "MI_B_5": "ᴹᴵᴰᴵ B₅",
  "MI_ALLOFF": "ᴹᴵᴰᴵ Notesᵒᶠᶠ",
  "MI_OCT_N2": "ᴹᴵᴰᴵ Oct₋₂",
  "MI_OCT_N1": "ᴹᴵᴰᴵ Oct₋₁",
  "MI_OCT_0": "ᴹᴵᴰᴵ Oct₀",
  "MI_OCT_1": "ᴹᴵᴰᴵ Oct₊₁",
  "MI_OCT_2": "ᴹᴵᴰᴵ Oct₊₂",
  "MI_OCT_3": "ᴹᴵᴰᴵ Oct₊₃",
  "MI_OCT_4": "ᴹᴵᴰᴵ Oct₊₄",
  "MI_OCT_5": "ᴹᴵᴰᴵ Oct₊₅",
  "MI_OCT_6": "ᴹᴵᴰᴵ Oct₊₆",
  "MI_OCT_7": "ᴹᴵᴰᴵ Oct₊₇",
  "MI_OCTD": "ᴹᴵᴰᴵ Octᴰᴺ",
  "MI_OCTU": "ᴹᴵᴰᴵ Octᵁᴾ",
  "MI_TRNS_N6": "ᴹᴵᴰᴵ Trans₋₆",
  "MI_TRNS_N5": "ᴹᴵᴰᴵ Trans₋₅",
  "MI_TRNS_N4": "ᴹᴵᴰᴵ Trans₋₄",
  "MI_TRNS_N3": "ᴹᴵᴰᴵ Trans₋₃",
  "MI_TRNS_N2": "ᴹᴵᴰᴵ Trans₋₂",
  "MI_TRNS_N1": "ᴹᴵᴰᴵ Trans₋₁",
  "MI_TRNS_0": "ᴹᴵᴰᴵ Trans₀",
  "MI_TRNS_1": "ᴹᴵᴰᴵ Trans₊₁",
  "MI_TRNS_2": "ᴹᴵᴰᴵ Trans₊₂",
  "MI_TRNS_3": "ᴹᴵᴰᴵ Trans₊₃",
  "MI_TRNS_4": "ᴹᴵᴰᴵ Trans₊₄",
  "MI_TRNS_5": "ᴹᴵᴰᴵ Trans₊₅",
  "MI_TRNS_6": "ᴹᴵᴰᴵ Trans₊₆",
  "MI_TRNSD": "ᴹᴵᴰᴵ Transᴰᴺ",
  "MI_TRNSU": "ᴹᴵᴰᴵ Transᵁᴾ",
  "MI_VEL_1": "ᴹᴵᴰᴵ Vel₁",
  "MI_VEL_0": "ᴹᴵᴰᴵ Vel₁",
  "MI_VEL_2": "ᴹᴵᴰᴵ Vel₂",
  "MI_VEL_3": "ᴹᴵᴰᴵ Vel₃",
  "MI_VEL_4": "ᴹᴵᴰᴵ Vel₄",
  "MI_VEL_5": "ᴹᴵᴰᴵ Vel₅",
  "MI_VEL_6": "ᴹᴵᴰᴵ Vel₆",
  "MI_VEL_7": "ᴹᴵᴰᴵ Vel₇",
  "MI_VEL_8": "ᴹᴵᴰᴵ Vel₈",
  "MI_VEL_9": "ᴹᴵᴰᴵ Vel₉",
  "MI_VEL_10": "ᴹᴵᴰᴵ Vel₁₀",
  "MI_VELD": "ᴹᴵᴰᴵ Velᴰᴺ",
  "MI_VELU": "ᴹᴵᴰᴵ Velᵁᴾ",
  "MI_CH1": "ᴹᴵᴰᴵ CH₁",
  "MI_CH2": "ᴹᴵᴰᴵ CH₂",
  "MI_CH3": "ᴹᴵᴰᴵ CH₃",
  "MI_CH4": "ᴹᴵᴰᴵ CH₄",
  "MI_CH5": "ᴹᴵᴰᴵ CH₅",
  "MI_CH6": "ᴹᴵᴰᴵ CH₆",
  "MI_CH7": "ᴹᴵᴰᴵ CH₇",
  "MI_CH8": "ᴹᴵᴰᴵ CH₈",
  "MI_CH9": "ᴹᴵᴰᴵ CH₉",
  "MI_CH10": "ᴹᴵᴰᴵ CH₁₀",
  "MI_CH11": "ᴹᴵᴰᴵ CH₁₁",
  "MI_CH12": "ᴹᴵᴰᴵ CH₁₂",
  "MI_CH13": "ᴹᴵᴰᴵ CH₁₃",
  "MI_CH14": "ᴹᴵᴰᴵ CH₁₄",
  "MI_CH15": "ᴹᴵᴰᴵ CH₁₅",
  "MI_CH16": "ᴹᴵᴰᴵ CH₁₆",
  "MI_CHD": "ᴹᴵᴰᴵ CHᴰᴺ",
  "MI_CHU": "ᴹᴵᴰᴵ CHᵁᴾ",
  "MI_SUS": "ᴹᴵᴰᴵ Sust",
  "MI_PORT": "ᴹᴵᴰᴵ Port",
  "MI_SOST": "ᴹᴵᴰᴵ Sost",
  "MI_SOFT": "ᴹᴵᴰᴵ SPedal",
  "MI_LEG": "ᴹᴵᴰᴵ Legat",
  "MI_MOD": "ᴹᴵᴰᴵ Modul",
  "MI_MODSD": "ᴹᴵᴰᴵ Modulᴰᴺ",
  "MI_MODSU": "ᴹᴵᴰᴵ Modulᵁᴾ",
  "MI_BENDD": "ᴹᴵᴰᴵ Bendᴰᴺ",
  "MI_BENDU": "ᴹᴵᴰᴵ Bendᵁᴾ",
  "KC_DQUO": "DQUO",
  "FN_MO13": "FN_MO13",
  "FN_MO23": "FN_MO23",
  "QMK_LM_SHIFT": "QMK_LM_SHIFT",
  "QMK_LM_MASK": "QMK_LM_MASK",
};

/** Numeric keycode → QMK string name (simple/non-parametric keycodes only) */
export const VIAL_NUMERIC: Record<number, string> = {
  0x0000: "KC_NO",
  0x0001: "KC_TRNS",
  0x0004: "KC_A",
  0x0005: "KC_B",
  0x0005: "QMK_LM_SHIFT",
  0x0006: "KC_C",
  0x0007: "KC_D",
  0x0008: "KC_E",
  0x0009: "KC_F",
  0x000a: "KC_G",
  0x000b: "KC_H",
  0x000c: "KC_I",
  0x000d: "KC_J",
  0x000e: "KC_K",
  0x000f: "KC_L",
  0x0010: "KC_M",
  0x0011: "KC_N",
  0x0012: "KC_O",
  0x0013: "KC_P",
  0x0014: "KC_Q",
  0x0015: "KC_R",
  0x0016: "KC_S",
  0x0017: "KC_T",
  0x0018: "KC_U",
  0x0019: "KC_V",
  0x001a: "KC_W",
  0x001b: "KC_X",
  0x001c: "KC_Y",
  0x001d: "KC_Z",
  0x001e: "KC_1",
  0x001f: "KC_2",
  0x001f: "QMK_LM_MASK",
  0x0020: "KC_3",
  0x0021: "KC_4",
  0x0022: "KC_5",
  0x0023: "KC_6",
  0x0024: "KC_7",
  0x0025: "KC_8",
  0x0026: "KC_9",
  0x0027: "KC_0",
  0x0028: "KC_ENTER",
  0x0029: "KC_ESCAPE",
  0x002a: "KC_BSPACE",
  0x002b: "KC_TAB",
  0x002c: "KC_SPACE",
  0x002d: "KC_MINUS",
  0x002e: "KC_EQUAL",
  0x002f: "KC_LBRACKET",
  0x0030: "KC_RBRACKET",
  0x0031: "KC_BSLASH",
  0x0032: "KC_NONUS_HASH",
  0x0033: "KC_SCOLON",
  0x0034: "KC_QUOTE",
  0x0035: "KC_GRAVE",
  0x0036: "KC_COMMA",
  0x0037: "KC_DOT",
  0x0038: "KC_SLASH",
  0x0039: "KC_CAPSLOCK",
  0x003a: "KC_F1",
  0x003b: "KC_F2",
  0x003c: "KC_F3",
  0x003d: "KC_F4",
  0x003e: "KC_F5",
  0x003f: "KC_F6",
  0x0040: "KC_F7",
  0x0041: "KC_F8",
  0x0042: "KC_F9",
  0x0043: "KC_F10",
  0x0044: "KC_F11",
  0x0045: "KC_F12",
  0x0046: "KC_PSCREEN",
  0x0047: "KC_SCROLLLOCK",
  0x0048: "KC_PAUSE",
  0x0049: "KC_INSERT",
  0x004a: "KC_HOME",
  0x004b: "KC_PGUP",
  0x004c: "KC_DELETE",
  0x004d: "KC_END",
  0x004e: "KC_PGDOWN",
  0x004f: "KC_RIGHT",
  0x0050: "KC_LEFT",
  0x0051: "KC_DOWN",
  0x0052: "KC_UP",
  0x0053: "KC_NUMLOCK",
  0x0054: "KC_KP_SLASH",
  0x0055: "KC_KP_ASTERISK",
  0x0056: "KC_KP_MINUS",
  0x0057: "KC_KP_PLUS",
  0x0058: "KC_KP_ENTER",
  0x0059: "KC_KP_1",
  0x005a: "KC_KP_2",
  0x005b: "KC_KP_3",
  0x005c: "KC_KP_4",
  0x005d: "KC_KP_5",
  0x005e: "KC_KP_6",
  0x005f: "KC_KP_7",
  0x0060: "KC_KP_8",
  0x0061: "KC_KP_9",
  0x0062: "KC_KP_0",
  0x0063: "KC_KP_DOT",
  0x0064: "KC_NONUS_BSLASH",
  0x0065: "KC_APPLICATION",
  0x0067: "KC_KP_EQUAL",
  0x0068: "KC_F13",
  0x0069: "KC_F14",
  0x006a: "KC_F15",
  0x006b: "KC_F16",
  0x006c: "KC_F17",
  0x006d: "KC_F18",
  0x006e: "KC_F19",
  0x006f: "KC_F20",
  0x0070: "KC_F21",
  0x0071: "KC_F22",
  0x0072: "KC_F23",
  0x0073: "KC_F24",
  0x0074: "KC_EXEC",
  0x0075: "KC_HELP",
  0x0077: "KC_SLCT",
  0x0078: "KC_STOP",
  0x0079: "KC_AGIN",
  0x007a: "KC_UNDO",
  0x007b: "KC_CUT",
  0x007c: "KC_COPY",
  0x007d: "KC_PSTE",
  0x007e: "KC_FIND",
  0x0080: "KC__VOLUP",
  0x0081: "KC__VOLDOWN",
  0x0082: "KC_LCAP",
  0x0083: "KC_LNUM",
  0x0084: "KC_LSCR",
  0x0085: "KC_KP_COMMA",
  0x0087: "KC_RO",
  0x0088: "KC_KANA",
  0x0089: "KC_JYEN",
  0x008a: "KC_HENK",
  0x008b: "KC_MHEN",
  0x0090: "KC_LANG1",
  0x0091: "KC_LANG2",
  0x00a5: "KC_PWR",
  0x00a6: "KC_SLEP",
  0x00a7: "KC_WAKE",
  0x00a8: "KC_MUTE",
  0x00a9: "KC_VOLU",
  0x00aa: "KC_VOLD",
  0x00ab: "KC_MNXT",
  0x00ac: "KC_MPRV",
  0x00ad: "KC_MSTP",
  0x00ae: "KC_MPLY",
  0x00af: "KC_MSEL",
  0x00b0: "KC_EJCT",
  0x00b1: "KC_MAIL",
  0x00b2: "KC_CALC",
  0x00b3: "KC_MYCM",
  0x00b4: "KC_WSCH",
  0x00b5: "KC_WHOM",
  0x00b6: "KC_WBAK",
  0x00b7: "KC_WFWD",
  0x00b8: "KC_WSTP",
  0x00b9: "KC_WREF",
  0x00ba: "KC_WFAV",
  0x00bb: "KC_MFFD",
  0x00bc: "KC_MRWD",
  0x00bd: "KC_BRIU",
  0x00be: "KC_BRID",
  0x00cd: "KC_MS_U",
  0x00ce: "KC_MS_D",
  0x00cf: "KC_MS_L",
  0x00d0: "KC_MS_R",
  0x00d1: "KC_BTN1",
  0x00d2: "KC_BTN2",
  0x00d3: "KC_BTN3",
  0x00d4: "KC_BTN4",
  0x00d5: "KC_BTN5",
  0x00d9: "KC_WH_U",
  0x00da: "KC_WH_D",
  0x00db: "KC_WH_L",
  0x00dc: "KC_WH_R",
  0x00dd: "KC_ACL0",
  0x00de: "KC_ACL1",
  0x00df: "KC_ACL2",
  0x00e0: "KC_LCTRL",
  0x00e1: "KC_LSHIFT",
  0x00e2: "KC_LALT",
  0x00e3: "KC_LGUI",
  0x00e4: "KC_RCTRL",
  0x00e5: "KC_RSHIFT",
  0x00e6: "KC_RALT",
  0x00e7: "KC_RGUI",
  0x021e: "KC_EXLM",
  0x021f: "KC_AT",
  0x0220: "KC_HASH",
  0x0221: "KC_DLR",
  0x0222: "KC_PERC",
  0x0223: "KC_CIRC",
  0x0224: "KC_AMPR",
  0x0225: "KC_ASTR",
  0x0226: "KC_LPRN",
  0x0227: "KC_RPRN",
  0x022d: "KC_UNDS",
  0x022e: "KC_PLUS",
  0x022f: "KC_LCBR",
  0x0230: "KC_RCBR",
  0x0231: "KC_PIPE",
  0x0233: "KC_COLN",
  0x0234: "KC_DQUO",
  0x0235: "KC_TILD",
  0x0236: "KC_LT",
  0x0237: "KC_GT",
  0x0238: "KC_QUES",
  0x52a1: "OSM(MOD_LCTL)",
  0x52a2: "OSM(MOD_LSFT)",
  0x52a3: "OSM(MOD_LCTL|MOD_LSFT)",
  0x52a4: "OSM(MOD_LALT)",
  0x52a5: "OSM(MOD_LCTL|MOD_LALT)",
  0x52a6: "OSM(MOD_LSFT|MOD_LALT)",
  0x52a7: "OSM(MOD_MEH)",
  0x52a8: "OSM(MOD_LGUI)",
  0x52a9: "OSM(MOD_LCTL|MOD_LGUI)",
  0x52aa: "OSM(MOD_LSFT|MOD_LGUI)",
  0x52ab: "OSM(MOD_LCTL|MOD_LSFT|MOD_LGUI)",
  0x52ac: "OSM(MOD_LALT|MOD_LGUI)",
  0x52ad: "OSM(MOD_LCTL|MOD_LALT|MOD_LGUI)",
  0x52ae: "OSM(MOD_LSFT|MOD_LALT|MOD_LGUI)",
  0x52af: "OSM(MOD_HYPR)",
  0x52b1: "OSM(MOD_RCTL)",
  0x52b2: "OSM(MOD_RSFT)",
  0x52b3: "OSM(MOD_RCTL|MOD_RSFT)",
  0x52b4: "OSM(MOD_RALT)",
  0x52b5: "OSM(MOD_RCTL|MOD_RALT)",
  0x52b6: "OSM(MOD_RSFT|MOD_RALT)",
  0x52b7: "OSM(MOD_RCTL|MOD_RSFT|MOD_RALT)",
  0x52b8: "OSM(MOD_RGUI)",
  0x52b9: "OSM(MOD_RCTL|MOD_RGUI)",
  0x52ba: "OSM(MOD_RSFT|MOD_RGUI)",
  0x52bb: "OSM(MOD_RCTL|MOD_RSFT|MOD_RGUI)",
  0x52bc: "OSM(MOD_RALT|MOD_RGUI)",
  0x52bd: "OSM(MOD_RCTL|MOD_RALT|MOD_RGUI)",
  0x52be: "OSM(MOD_RSFT|MOD_RALT|MOD_RGUI)",
  0x52bf: "OSM(MOD_RCTL|MOD_RSFT|MOD_RALT|MOD_RGUI)",
  0x7000: "MAGIC_SWAP_CONTROL_CAPSLOCK",
  0x7001: "MAGIC_UNSWAP_CONTROL_CAPSLOCK",
  0x7003: "MAGIC_UNCAPSLOCK_TO_CONTROL",
  0x7004: "MAGIC_CAPSLOCK_TO_CONTROL",
  0x7005: "MAGIC_SWAP_LALT_LGUI",
  0x7006: "MAGIC_UNSWAP_LALT_LGUI",
  0x7007: "MAGIC_SWAP_RALT_RGUI",
  0x7008: "MAGIC_UNSWAP_RALT_RGUI",
  0x7009: "MAGIC_UNNO_GUI",
  0x700a: "MAGIC_NO_GUI",
  0x700b: "MAGIC_TOGGLE_GUI",
  0x700c: "MAGIC_SWAP_GRAVE_ESC",
  0x700d: "MAGIC_UNSWAP_GRAVE_ESC",
  0x700e: "MAGIC_SWAP_BACKSLASH_BACKSPACE",
  0x700f: "MAGIC_UNSWAP_BACKSLASH_BACKSPACE",
  0x7011: "MAGIC_HOST_NKRO",
  0x7012: "MAGIC_UNHOST_NKRO",
  0x7013: "MAGIC_TOGGLE_NKRO",
  0x7014: "MAGIC_SWAP_ALT_GUI",
  0x7015: "MAGIC_UNSWAP_ALT_GUI",
  0x7016: "MAGIC_TOGGLE_ALT_GUI",
  0x7017: "MAGIC_SWAP_LCTL_LGUI",
  0x7018: "MAGIC_UNSWAP_LCTL_LGUI",
  0x7019: "MAGIC_SWAP_RCTL_RGUI",
  0x701a: "MAGIC_UNSWAP_RCTL_RGUI",
  0x701b: "MAGIC_SWAP_CTL_GUI",
  0x701c: "MAGIC_UNSWAP_CTL_GUI",
  0x701d: "MAGIC_TOGGLE_CTL_GUI",
  0x701e: "MAGIC_EE_HANDS_LEFT",
  0x701f: "MAGIC_EE_HANDS_RIGHT",
  0x7103: "MI_C",
  0x7104: "MI_Cs",
  0x7105: "MI_D",
  0x7106: "MI_Ds",
  0x7107: "MI_E",
  0x7108: "MI_F",
  0x7109: "MI_Fs",
  0x710a: "MI_G",
  0x710b: "MI_Gs",
  0x710c: "MI_A",
  0x710d: "MI_As",
  0x710e: "MI_B",
  0x710f: "MI_C_1",
  0x7110: "MI_Cs_1",
  0x7111: "MI_D_1",
  0x7112: "MI_Ds_1",
  0x7113: "MI_E_1",
  0x7114: "MI_F_1",
  0x7115: "MI_Fs_1",
  0x7116: "MI_G_1",
  0x7117: "MI_Gs_1",
  0x7118: "MI_A_1",
  0x7119: "MI_As_1",
  0x711a: "MI_B_1",
  0x711b: "MI_C_2",
  0x711c: "MI_Cs_2",
  0x711d: "MI_D_2",
  0x711e: "MI_Ds_2",
  0x711f: "MI_E_2",
  0x7120: "MI_F_2",
  0x7121: "MI_Fs_2",
  0x7122: "MI_G_2",
  0x7123: "MI_Gs_2",
  0x7124: "MI_A_2",
  0x7125: "MI_As_2",
  0x7126: "MI_B_2",
  0x7127: "MI_C_3",
  0x7128: "MI_Cs_3",
  0x7129: "MI_D_3",
  0x712a: "MI_Ds_3",
  0x712b: "MI_E_3",
  0x712c: "MI_F_3",
  0x712d: "MI_Fs_3",
  0x712e: "MI_G_3",
  0x712f: "MI_Gs_3",
  0x7130: "MI_A_3",
  0x7131: "MI_As_3",
  0x7132: "MI_B_3",
  0x7133: "MI_C_4",
  0x7134: "MI_Cs_4",
  0x7135: "MI_D_4",
  0x7136: "MI_Ds_4",
  0x7137: "MI_E_4",
  0x7138: "MI_F_4",
  0x7139: "MI_Fs_4",
  0x713a: "MI_G_4",
  0x713b: "MI_Gs_4",
  0x713c: "MI_A_4",
  0x713d: "MI_As_4",
  0x713e: "MI_B_4",
  0x713f: "MI_C_5",
  0x7140: "MI_Cs_5",
  0x7141: "MI_D_5",
  0x7142: "MI_Ds_5",
  0x7143: "MI_E_5",
  0x7144: "MI_F_5",
  0x7145: "MI_Fs_5",
  0x7146: "MI_G_5",
  0x7147: "MI_Gs_5",
  0x7148: "MI_A_5",
  0x7149: "MI_As_5",
  0x714a: "MI_B_5",
  0x714b: "MI_OCT_N2",
  0x714c: "MI_OCT_N1",
  0x714d: "MI_OCT_0",
  0x714e: "MI_OCT_1",
  0x714f: "MI_OCT_2",
  0x7150: "MI_OCT_3",
  0x7151: "MI_OCT_4",
  0x7152: "MI_OCT_5",
  0x7153: "MI_OCT_6",
  0x7154: "MI_OCT_7",
  0x7155: "MI_OCTD",
  0x7156: "MI_OCTU",
  0x7157: "MI_TRNS_N6",
  0x7158: "MI_TRNS_N5",
  0x7159: "MI_TRNS_N4",
  0x715a: "MI_TRNS_N3",
  0x715b: "MI_TRNS_N2",
  0x715c: "MI_TRNS_N1",
  0x715d: "MI_TRNS_0",
  0x715e: "MI_TRNS_1",
  0x715f: "MI_TRNS_2",
  0x7160: "MI_TRNS_3",
  0x7161: "MI_TRNS_4",
  0x7162: "MI_TRNS_5",
  0x7163: "MI_TRNS_6",
  0x7164: "MI_TRNSD",
  0x7165: "MI_TRNSU",
  0x7167: "MI_VEL_1",
  0x7168: "MI_VEL_2",
  0x7169: "MI_VEL_3",
  0x716a: "MI_VEL_4",
  0x716b: "MI_VEL_5",
  0x716c: "MI_VEL_6",
  0x716d: "MI_VEL_7",
  0x716e: "MI_VEL_8",
  0x716f: "MI_VEL_9",
  0x7170: "MI_VEL_10",
  0x7171: "MI_VELD",
  0x7172: "MI_VELU",
  0x7173: "MI_CH1",
  0x7174: "MI_CH2",
  0x7175: "MI_CH3",
  0x7176: "MI_CH4",
  0x7177: "MI_CH5",
  0x7178: "MI_CH6",
  0x7179: "MI_CH7",
  0x717a: "MI_CH8",
  0x717b: "MI_CH9",
  0x717c: "MI_CH10",
  0x717d: "MI_CH11",
  0x717e: "MI_CH12",
  0x717f: "MI_CH13",
  0x7180: "MI_CH14",
  0x7181: "MI_CH15",
  0x7182: "MI_CH16",
  0x7183: "MI_CHD",
  0x7184: "MI_CHU",
  0x7185: "MI_ALLOFF",
  0x7186: "MI_SUS",
  0x7187: "MI_PORT",
  0x7188: "MI_SOST",
  0x7189: "MI_SOFT",
  0x718a: "MI_LEG",
  0x718b: "MI_MOD",
  0x718c: "MI_MODSD",
  0x718d: "MI_MODSU",
  0x718e: "MI_BENDD",
  0x718f: "MI_BENDU",
  0x7480: "AU_ON",
  0x7481: "AU_OFF",
  0x7482: "AU_TOG",
  0x748a: "CLICKY_TOGGLE",
  0x748d: "CLICKY_UP",
  0x748e: "CLICKY_DOWN",
  0x748f: "CLICKY_RESET",
  0x7490: "MU_ON",
  0x7491: "MU_OFF",
  0x7492: "MU_TOG",
  0x7493: "MU_MOD",
  0x7800: "BL_ON",
  0x7801: "BL_OFF",
  0x7802: "BL_TOGG",
  0x7803: "BL_DEC",
  0x7804: "BL_INC",
  0x7805: "BL_STEP",
  0x7806: "BL_BRTG",
  0x7820: "RGB_TOG",
  0x7821: "RGB_MOD",
  0x7822: "RGB_RMOD",
  0x7823: "RGB_HUI",
  0x7824: "RGB_HUD",
  0x7825: "RGB_SAI",
  0x7826: "RGB_SAD",
  0x7827: "RGB_VAI",
  0x7828: "RGB_VAD",
  0x7829: "RGB_SPI",
  0x782a: "RGB_SPD",
  0x782b: "RGB_M_P",
  0x782c: "RGB_M_B",
  0x782d: "RGB_M_R",
  0x782e: "RGB_M_SW",
  0x782f: "RGB_M_SN",
  0x7830: "RGB_M_K",
  0x7831: "RGB_M_X",
  0x7832: "RGB_M_G",
  0x7833: "RGB_M_T",
  0x7840: "RM_ON",
  0x7841: "RM_OFF",
  0x7842: "RM_TOGG",
  0x7843: "RM_NEXT",
  0x7844: "RM_PREV",
  0x7845: "RM_HUEU",
  0x7846: "RM_HUED",
  0x7847: "RM_SATU",
  0x7848: "RM_SATD",
  0x7849: "RM_VALU",
  0x784a: "RM_VALD",
  0x784b: "RM_SPDU",
  0x784c: "RM_SPDD",
  0x7c00: "QK_BOOT",
  0x7c01: "QK_REBOOT",
  0x7c03: "QK_CLEAR_EEPROM",
  0x7c10: "KC_ASDN",
  0x7c11: "KC_ASUP",
  0x7c12: "KC_ASRP",
  0x7c13: "KC_ASON",
  0x7c14: "KC_ASOFF",
  0x7c15: "KC_ASTG",
  0x7c16: "KC_GESC",
  0x7c18: "KC_LCPO",
  0x7c19: "KC_RCPC",
  0x7c1a: "KC_LSPO",
  0x7c1b: "KC_RSPC",
  0x7c1c: "KC_LAPO",
  0x7c1d: "KC_RAPC",
  0x7c1e: "KC_SFTENT",
  0x7c40: "HPT_ON",
  0x7c41: "HPT_OFF",
  0x7c42: "HPT_TOG",
  0x7c43: "HPT_RST",
  0x7c44: "HPT_FBK",
  0x7c45: "HPT_BUZ",
  0x7c46: "HPT_MODI",
  0x7c47: "HPT_MODD",
  0x7c48: "HPT_CONT",
  0x7c49: "HPT_CONI",
  0x7c4a: "HPT_COND",
  0x7c4b: "HPT_DWLI",
  0x7c4c: "HPT_DWLD",
  0x7c50: "CMB_ON",
  0x7c51: "CMB_OFF",
  0x7c52: "CMB_TOG",
  0x7c53: "DYN_REC_START1",
  0x7c54: "DYN_REC_START2",
  0x7c55: "DYN_REC_STOP",
  0x7c56: "DYN_MACRO_PLAY1",
  0x7c57: "DYN_MACRO_PLAY2",
  0x7c73: "QK_CAPS_WORD_TOGGLE",
  0x7c77: "FN_MO13",
  0x7c78: "FN_MO23",
  0x7c79: "QK_REPEAT_KEY",
  0x7c7a: "QK_ALT_REPEAT_KEY",
};
